import { DynamicModule, Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { generateDataSourceOptions } from './persistence';
import { IDbOptions } from '../common';
import Entities from './persistence/entities';
import Seeds from './persistence/seeds';
import { EntityMapperProfile } from './persistence/mappers';

import {
  OrganizationRepo,
  StoreRepo,
  CategoryRepo,
  ProductRepo,
  SupplierRepo,
  InventoryRepo,
  PurchaseOrderRepo,
  ActivityLogRepo,
  BillRepo,
  BillItemRepo,
  CustomerRepo,
  ExpenseRepo,
  InvoiceRepo,
  ItemReturnRepo,
  NotificationRepo,
  OrderRepo,
  PaymentTransactionRepo,
  PlatformConfigurationRepo,
  PurchaseItemRepo,
  ReportGenerationLogRepo,
  RoleRepo,
  StockMovementRepo,
  StockTransferRepo,
  UserRoleRepo,
  UserRepo,
  OrgMemberRepo,
  ProductImageRepo,
  ProductSupplierRepo,
  LocationRepo,
  ProductLogRepo,
  UnpublishedStockRepo,
  UnpublishedStockMovementRepo,
  CountryRepo,
  StateRepo,
  CityRepo,
  CurrencyRepo,
  LanguageRepo,
} from './persistence';

import {
  ACTIVITY_LOG_REPO,
  BILL_REPO,
  BILL_ITEM_REPO,
  CATEGORY_REPO,
  CUSTOMER_REPO,
  EXPENSE_REPO,
  INVENTORY_REPO,
  INVOICE_REPO,
  ITEM_RETURN_REPO,
  NOTIFICATION_REPO,
  ORGANIZATION_REPO,
  ORDER_REPO,
  PAYMENT_TRANSACTION_REPO,
  PLATFORM_CONFIGURATION_REPO,
  PRODUCT_REPO,
  PURCHASE_ITEM_REPO,
  PURCHASE_ORDER_REPO,
  REPORT_GENERATION_LOG_REPO,
  ROLE_REPO,
  STOCK_MOVEMENT_REPO,
  STOCK_TRANSFER_REPO,
  STORE_REPO,
  SUPPLIER_REPO,
  USER_REPO,
  USER_ROLE_REPO,
  ORG_MEMBER_REPO,
  PRODUCT_IMAGE_REPO,
  PRODUCT_SUPPLIER_REPO,
  LOCATION_REPO,
  PRODUCT_LOG_REPO,
  UNPUBLISHED_STOCK_REPO,
  UNPUBLISHED_STOCK_MOVEMENT_REPO,
  COUNTRY_REPO,
  STATE_REPO,
  CITY_REPO,
  CURRENCY_REPO,
  LANGUAGE_REPO,
} from '../application/constants';

@Module({})
export class InfrastructureModule {
  public static forRoot(): DynamicModule {
    return {
      global: true,
      module: InfrastructureModule,
      imports: [
        TypeOrmModule.forRootAsync({
          imports: [ConfigModule],
          inject: [ConfigService],
          useFactory: (configService: ConfigService) => {
            const opts = configService.get<IDbOptions>('database');
            return {
              ...generateDataSourceOptions(opts),
              retryAttempts: opts?.retryAttempts,
              retryDelay: opts?.retryDelay,
              toRetry: opts?.toRetry,
            };
          },
        }),
        TypeOrmModule.forFeature([...Entities]),
      ],
      providers: [
        EntityMapperProfile,
        ...Seeds,
        { provide: ORGANIZATION_REPO, useClass: OrganizationRepo },
        { provide: STORE_REPO, useClass: StoreRepo },
        { provide: CATEGORY_REPO, useClass: CategoryRepo },
        { provide: PRODUCT_REPO, useClass: ProductRepo },
        { provide: SUPPLIER_REPO, useClass: SupplierRepo },
        { provide: INVENTORY_REPO, useClass: InventoryRepo },
        { provide: PURCHASE_ORDER_REPO, useClass: PurchaseOrderRepo },
        { provide: ACTIVITY_LOG_REPO, useClass: ActivityLogRepo },
        { provide: BILL_REPO, useClass: BillRepo },
        { provide: BILL_ITEM_REPO, useClass: BillItemRepo },
        { provide: CUSTOMER_REPO, useClass: CustomerRepo },
        { provide: EXPENSE_REPO, useClass: ExpenseRepo },
        { provide: INVOICE_REPO, useClass: InvoiceRepo },
        { provide: ITEM_RETURN_REPO, useClass: ItemReturnRepo },
        { provide: NOTIFICATION_REPO, useClass: NotificationRepo },
        { provide: ORDER_REPO, useClass: OrderRepo },
        { provide: PAYMENT_TRANSACTION_REPO, useClass: PaymentTransactionRepo },
        { provide: PLATFORM_CONFIGURATION_REPO, useClass: PlatformConfigurationRepo },
        { provide: PURCHASE_ITEM_REPO, useClass: PurchaseItemRepo },
        { provide: REPORT_GENERATION_LOG_REPO, useClass: ReportGenerationLogRepo },
        { provide: ROLE_REPO, useClass: RoleRepo },
        { provide: STOCK_MOVEMENT_REPO, useClass: StockMovementRepo },
        { provide: STOCK_TRANSFER_REPO, useClass: StockTransferRepo },
        { provide: USER_REPO, useClass: UserRepo },
        { provide: USER_ROLE_REPO, useClass: UserRoleRepo },
        { provide: ORG_MEMBER_REPO, useClass: OrgMemberRepo },
        { provide: PRODUCT_IMAGE_REPO, useClass: ProductImageRepo },
        { provide: PRODUCT_SUPPLIER_REPO, useClass: ProductSupplierRepo },
        { provide: LOCATION_REPO, useClass: LocationRepo },
        { provide: PRODUCT_LOG_REPO, useClass: ProductLogRepo },
        { provide: UNPUBLISHED_STOCK_REPO, useClass: UnpublishedStockRepo },
        { provide: UNPUBLISHED_STOCK_MOVEMENT_REPO, useClass: UnpublishedStockMovementRepo },
        { provide: COUNTRY_REPO, useClass: CountryRepo },
        { provide: STATE_REPO, useClass: StateRepo },
        { provide: CITY_REPO, useClass: CityRepo },
        { provide: CURRENCY_REPO, useClass: CurrencyRepo },
        { provide: LANGUAGE_REPO, useClass: LanguageRepo },
      ],
      exports: [
        EntityMapperProfile,
        ORGANIZATION_REPO,
        STORE_REPO,
        CATEGORY_REPO,
        PRODUCT_REPO,
        SUPPLIER_REPO,
        INVENTORY_REPO,
        PURCHASE_ORDER_REPO,
        ACTIVITY_LOG_REPO,
        BILL_REPO,
        BILL_ITEM_REPO,
        CUSTOMER_REPO,
        EXPENSE_REPO,
        INVOICE_REPO,
        ITEM_RETURN_REPO,
        NOTIFICATION_REPO,
        ORDER_REPO,
        PAYMENT_TRANSACTION_REPO,
        PLATFORM_CONFIGURATION_REPO,
        PURCHASE_ITEM_REPO,
        REPORT_GENERATION_LOG_REPO,
        ROLE_REPO,
        STOCK_MOVEMENT_REPO,
        STOCK_TRANSFER_REPO,
        USER_REPO,
        USER_ROLE_REPO,
        ORG_MEMBER_REPO,
        PRODUCT_IMAGE_REPO,
        PRODUCT_SUPPLIER_REPO,
        LOCATION_REPO,
        PRODUCT_LOG_REPO,
        UNPUBLISHED_STOCK_REPO,
        UNPUBLISHED_STOCK_MOVEMENT_REPO,
        COUNTRY_REPO,
        STATE_REPO,
        CITY_REPO,
        CURRENCY_REPO,
        LANGUAGE_REPO,
      ],
    };
  }
}
