import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1786218933007 implements MigrationInterface {
    name = 'Migration1786218933007'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "core"."vehicle_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_vehicle_types" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."vehicle_brands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "brand_name" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_vehicle_brands" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."fuel_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_fuel_types" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "core"."vehicles_status_enum" AS ENUM('available', 'in_transit', 'maintenance', 'idle', 'out_of_service')`);
        await queryRunner.query(`CREATE TABLE "core"."vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_number" character varying(30) NOT NULL, "vin_number" character varying(100), "registration_number" character varying(50), "company_id" uuid NOT NULL, "vehicle_type_id" uuid NOT NULL, "brand_id" uuid NOT NULL, "model" character varying(100), "manufacture_year" integer, "color" character varying(50), "fuel_type_id" uuid NOT NULL, "tank_capacity" numeric(10,2), "payload_capacity" numeric(10,2), "mileage" numeric(10,2), "purchase_date" date, "purchase_price" numeric(12,2), "insurance_expiry" date, "registration_expiry" date, "status" "core"."vehicles_status_enum" NOT NULL DEFAULT 'available', "image_url" text, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_97a57b7389989efc352bef8af3a" UNIQUE ("vehicle_number"), CONSTRAINT "PK_vehicles" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "core"."drivers_status_enum" AS ENUM('active', 'inactive', 'on_trip', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "core"."drivers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "employee_id" character varying(50), "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(150), "license_number" character varying(50) NOT NULL, "license_type" character varying(50), "license_expiry" date, "joining_date" date, "experience_years" integer, "blood_group" character varying(5), "address" text, "emergency_contact" character varying(100), "status" "core"."drivers_status_enum" NOT NULL DEFAULT 'active', "profile_image" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_47543bd8e5e11a094ded9a56e98" UNIQUE ("license_number"), CONSTRAINT "PK_drivers" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."vehicle_driver_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "driver_id" uuid NOT NULL, "assigned_date" TIMESTAMP NOT NULL, "released_date" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_vehicle_driver_assignments" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."vehicle_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "latitude" numeric(10,8) NOT NULL, "longitude" numeric(11,8) NOT NULL, "speed" numeric(10,2), "heading" numeric(10,2), "altitude" numeric(10,2), "fuel_level" numeric(10,2), "odometer" numeric(15,2), "engine_status" character varying(50), "gps_time" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_vehicle_locations" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "core"."trips_trip_status_enum" AS ENUM('scheduled', 'in_transit', 'completed', 'cancelled', 'delayed')`);
        await queryRunner.query(`CREATE TABLE "core"."trips" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trip_number" character varying(50) NOT NULL, "vehicle_id" uuid NOT NULL, "driver_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "pickup_location" text NOT NULL, "drop_location" text NOT NULL, "start_datetime" TIMESTAMP NOT NULL, "end_datetime" TIMESTAMP, "estimated_distance" numeric(10,2), "actual_distance" numeric(10,2), "estimated_duration" character varying(50), "actual_duration" character varying(50), "trip_status" "core"."trips_trip_status_enum" NOT NULL DEFAULT 'scheduled', "priority" character varying(20) NOT NULL DEFAULT 'medium', "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "UQ_22afe83e1f09437f58906bb38de" UNIQUE ("trip_number"), CONSTRAINT "PK_trips" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."trip_checkpoints" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trip_id" uuid NOT NULL, "location" text NOT NULL, "latitude" numeric(10,8) NOT NULL, "longitude" numeric(11,8) NOT NULL, "arrival_time" TIMESTAMP, "departure_time" TIMESTAMP, "sequence" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_trip_checkpoints" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."trip_goods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trip_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(10,2) NOT NULL, "weight" numeric(10,2), "volume" numeric(10,2), "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_trip_goods" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "core"."trip_events_event_type_enum" AS ENUM('started', 'loading', 'unloading', 'reached', 'fuel_added', 'delay', 'maintenance')`);
        await queryRunner.query(`CREATE TABLE "core"."trip_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trip_id" uuid NOT NULL, "event_type" "core"."trip_events_event_type_enum" NOT NULL, "title" character varying(100) NOT NULL, "description" text, "latitude" numeric(10,8), "longitude" numeric(11,8), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_trip_events" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."fuel_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "driver_id" uuid NOT NULL, "trip_id" uuid, "fuel_station" character varying(100) NOT NULL, "fuel_quantity" numeric(10,2) NOT NULL, "price_per_liter" numeric(10,2) NOT NULL, "total_cost" numeric(10,2) NOT NULL, "odometer" numeric(15,2), "payment_mode" character varying(50), "receipt_image" text, "filled_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fuel_transactions" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."maintenance_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_maintenance_types" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "core"."maintenance_status_enum" AS ENUM('pending', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "core"."maintenance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "maintenance_type_id" uuid NOT NULL, "service_center" character varying(100) NOT NULL, "description" text, "cost" numeric(12,2) NOT NULL, "service_date" date NOT NULL, "next_service_date" date, "odometer" numeric(15,2), "invoice_number" character varying(50), "status" "core"."maintenance_status_enum" NOT NULL DEFAULT 'pending', "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_maintenance" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."maintenance_parts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "maintenance_id" uuid NOT NULL, "part_name" character varying(100) NOT NULL, "quantity" numeric(10,2) NOT NULL, "price" numeric(10,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_maintenance_parts" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "core"."vehicle_expenses_expense_type_enum" AS ENUM('fuel', 'toll', 'parking', 'insurance', 'tax', 'washing', 'repair', 'other')`);
        await queryRunner.query(`CREATE TABLE "core"."vehicle_expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "trip_id" uuid, "expense_type" "core"."vehicle_expenses_expense_type_enum" NOT NULL, "amount" numeric(12,2) NOT NULL, "expense_date" date NOT NULL, "remarks" text, "attachment" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_vehicle_expenses" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "core"."vehicle_documents_document_type_enum" AS ENUM('registration', 'insurance', 'license', 'pollution', 'fitness', 'permit', 'other')`);
        await queryRunner.query(`CREATE TABLE "core"."vehicle_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "document_type" "core"."vehicle_documents_document_type_enum" NOT NULL, "document_number" character varying(100), "issue_date" date, "expiry_date" date, "file_url" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_vehicle_documents" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "core"."driver_documents_document_type_enum" AS ENUM('registration', 'insurance', 'license', 'pollution', 'fitness', 'permit', 'other')`);
        await queryRunner.query(`CREATE TABLE "core"."driver_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driver_id" uuid NOT NULL, "document_type" "core"."driver_documents_document_type_enum" NOT NULL, "file_url" text NOT NULL, "expiry_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_driver_documents" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."vehicle_insurance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "provider" character varying(100) NOT NULL, "policy_number" character varying(100) NOT NULL, "start_date" date NOT NULL, "expiry_date" date NOT NULL, "premium" numeric(12,2) NOT NULL, "coverage" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_vehicle_insurance" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."transportation_order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(10,2) NOT NULL, "weight" numeric(10,2), "volume" numeric(10,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_transportation_order_items" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "core"."transportation_orders_status_enum" AS ENUM('pending', 'confirmed', 'in_transit', 'delivered', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "core"."transportation_orders_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "core"."transportation_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_number" character varying(50) NOT NULL, "customer_id" uuid NOT NULL, "pickup_address" text NOT NULL, "delivery_address" text NOT NULL, "expected_delivery" TIMESTAMP NOT NULL, "status" "core"."transportation_orders_status_enum" NOT NULL DEFAULT 'pending', "priority" "core"."transportation_orders_priority_enum" NOT NULL DEFAULT 'medium', "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "UQ_24e49ec41e7d5d6acd94a36f41a" UNIQUE ("order_number"), CONSTRAINT "PK_transportation_orders" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."gps_devices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "device_number" character varying(50) NOT NULL, "imei" character varying(100) NOT NULL, "vehicle_id" uuid, "provider" character varying(100), "status" character varying(50) NOT NULL DEFAULT 'active', "last_sync" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "UQ_e4f4ae395c1315ed738dca33774" UNIQUE ("device_number"), CONSTRAINT "UQ_a5cfb10e3dedb4f64a646fa1b42" UNIQUE ("imei"), CONSTRAINT "PK_gps_devices" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "core"."alerts_alert_type_enum" AS ENUM('overspeed', 'low_fuel', 'offline', 'maintenance_due', 'insurance_expiring')`);
        await queryRunner.query(`CREATE TYPE "core"."alerts_severity_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "core"."alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid, "driver_id" uuid, "alert_type" "core"."alerts_alert_type_enum" NOT NULL, "severity" "core"."alerts_severity_enum" NOT NULL, "message" text NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'unread', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_alerts" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "core"."vehicles" ADD CONSTRAINT "FK__vehicles__organizations" FOREIGN KEY ("company_id") REFERENCES "core"."organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."vehicles" ADD CONSTRAINT "FK__vehicles__vehicle_types" FOREIGN KEY ("vehicle_type_id") REFERENCES "core"."vehicle_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."vehicles" ADD CONSTRAINT "FK__vehicles__vehicle_brands" FOREIGN KEY ("brand_id") REFERENCES "core"."vehicle_brands"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."vehicles" ADD CONSTRAINT "FK__vehicles__fuel_types" FOREIGN KEY ("fuel_type_id") REFERENCES "core"."fuel_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."drivers" ADD CONSTRAINT "FK__drivers__organizations" FOREIGN KEY ("organization_id") REFERENCES "core"."organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_driver_assignments" ADD CONSTRAINT "FK__vehicle_driver_assignments__vehicles" FOREIGN KEY ("vehicle_id") REFERENCES "core"."vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_driver_assignments" ADD CONSTRAINT "FK__vehicle_driver_assignments__drivers" FOREIGN KEY ("driver_id") REFERENCES "core"."drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_locations" ADD CONSTRAINT "FK__vehicle_locations__vehicles" FOREIGN KEY ("vehicle_id") REFERENCES "core"."vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."trips" ADD CONSTRAINT "FK__trips__vehicles" FOREIGN KEY ("vehicle_id") REFERENCES "core"."vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."trips" ADD CONSTRAINT "FK__trips__drivers" FOREIGN KEY ("driver_id") REFERENCES "core"."drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."trips" ADD CONSTRAINT "FK__trips__customers" FOREIGN KEY ("customer_id") REFERENCES "core"."customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."trip_checkpoints" ADD CONSTRAINT "FK__trip_checkpoints__trips" FOREIGN KEY ("trip_id") REFERENCES "core"."trips"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."trip_goods" ADD CONSTRAINT "FK__trip_goods__trips" FOREIGN KEY ("trip_id") REFERENCES "core"."trips"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."trip_goods" ADD CONSTRAINT "FK__trip_goods__products" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."trip_events" ADD CONSTRAINT "FK__trip_events__trips" FOREIGN KEY ("trip_id") REFERENCES "core"."trips"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."fuel_transactions" ADD CONSTRAINT "FK__fuel_transactions__vehicles" FOREIGN KEY ("vehicle_id") REFERENCES "core"."vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."fuel_transactions" ADD CONSTRAINT "FK__fuel_transactions__drivers" FOREIGN KEY ("driver_id") REFERENCES "core"."drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."fuel_transactions" ADD CONSTRAINT "FK__fuel_transactions__trips" FOREIGN KEY ("trip_id") REFERENCES "core"."trips"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."maintenance" ADD CONSTRAINT "FK__maintenance__vehicles" FOREIGN KEY ("vehicle_id") REFERENCES "core"."vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."maintenance" ADD CONSTRAINT "FK__maintenance__maintenance_types" FOREIGN KEY ("maintenance_type_id") REFERENCES "core"."maintenance_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."maintenance_parts" ADD CONSTRAINT "FK__maintenance_parts__maintenance" FOREIGN KEY ("maintenance_id") REFERENCES "core"."maintenance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_expenses" ADD CONSTRAINT "FK__vehicle_expenses__vehicles" FOREIGN KEY ("vehicle_id") REFERENCES "core"."vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_expenses" ADD CONSTRAINT "FK__vehicle_expenses__trips" FOREIGN KEY ("trip_id") REFERENCES "core"."trips"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_documents" ADD CONSTRAINT "FK__vehicle_documents__vehicles" FOREIGN KEY ("vehicle_id") REFERENCES "core"."vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."driver_documents" ADD CONSTRAINT "FK__driver_documents__drivers" FOREIGN KEY ("driver_id") REFERENCES "core"."drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_insurance" ADD CONSTRAINT "FK__vehicle_insurance__vehicles" FOREIGN KEY ("vehicle_id") REFERENCES "core"."vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."transportation_order_items" ADD CONSTRAINT "FK__transportation_order_items__transportation_orders" FOREIGN KEY ("order_id") REFERENCES "core"."transportation_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."transportation_order_items" ADD CONSTRAINT "FK__transportation_order_items__products" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."transportation_orders" ADD CONSTRAINT "FK__transportation_orders__customers" FOREIGN KEY ("customer_id") REFERENCES "core"."customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."gps_devices" ADD CONSTRAINT "FK__gps_devices__vehicles" FOREIGN KEY ("vehicle_id") REFERENCES "core"."vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."alerts" ADD CONSTRAINT "FK__alerts__vehicles" FOREIGN KEY ("vehicle_id") REFERENCES "core"."vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."alerts" ADD CONSTRAINT "FK__alerts__drivers" FOREIGN KEY ("driver_id") REFERENCES "core"."drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "core"."alerts" DROP CONSTRAINT "FK__alerts__drivers"`);
        await queryRunner.query(`ALTER TABLE "core"."alerts" DROP CONSTRAINT "FK__alerts__vehicles"`);
        await queryRunner.query(`ALTER TABLE "core"."gps_devices" DROP CONSTRAINT "FK__gps_devices__vehicles"`);
        await queryRunner.query(`ALTER TABLE "core"."transportation_orders" DROP CONSTRAINT "FK__transportation_orders__customers"`);
        await queryRunner.query(`ALTER TABLE "core"."transportation_order_items" DROP CONSTRAINT "FK__transportation_order_items__products"`);
        await queryRunner.query(`ALTER TABLE "core"."transportation_order_items" DROP CONSTRAINT "FK__transportation_order_items__transportation_orders"`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_insurance" DROP CONSTRAINT "FK__vehicle_insurance__vehicles"`);
        await queryRunner.query(`ALTER TABLE "core"."driver_documents" DROP CONSTRAINT "FK__driver_documents__drivers"`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_documents" DROP CONSTRAINT "FK__vehicle_documents__vehicles"`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_expenses" DROP CONSTRAINT "FK__vehicle_expenses__trips"`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_expenses" DROP CONSTRAINT "FK__vehicle_expenses__vehicles"`);
        await queryRunner.query(`ALTER TABLE "core"."maintenance_parts" DROP CONSTRAINT "FK__maintenance_parts__maintenance"`);
        await queryRunner.query(`ALTER TABLE "core"."maintenance" DROP CONSTRAINT "FK__maintenance__maintenance_types"`);
        await queryRunner.query(`ALTER TABLE "core"."maintenance" DROP CONSTRAINT "FK__maintenance__vehicles"`);
        await queryRunner.query(`ALTER TABLE "core"."fuel_transactions" DROP CONSTRAINT "FK__fuel_transactions__trips"`);
        await queryRunner.query(`ALTER TABLE "core"."fuel_transactions" DROP CONSTRAINT "FK__fuel_transactions__drivers"`);
        await queryRunner.query(`ALTER TABLE "core"."fuel_transactions" DROP CONSTRAINT "FK__fuel_transactions__vehicles"`);
        await queryRunner.query(`ALTER TABLE "core"."trip_events" DROP CONSTRAINT "FK__trip_events__trips"`);
        await queryRunner.query(`ALTER TABLE "core"."trip_goods" DROP CONSTRAINT "FK__trip_goods__products"`);
        await queryRunner.query(`ALTER TABLE "core"."trip_goods" DROP CONSTRAINT "FK__trip_goods__trips"`);
        await queryRunner.query(`ALTER TABLE "core"."trip_checkpoints" DROP CONSTRAINT "FK__trip_checkpoints__trips"`);
        await queryRunner.query(`ALTER TABLE "core"."trips" DROP CONSTRAINT "FK__trips__customers"`);
        await queryRunner.query(`ALTER TABLE "core"."trips" DROP CONSTRAINT "FK__trips__drivers"`);
        await queryRunner.query(`ALTER TABLE "core"."trips" DROP CONSTRAINT "FK__trips__vehicles"`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_locations" DROP CONSTRAINT "FK__vehicle_locations__vehicles"`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_driver_assignments" DROP CONSTRAINT "FK__vehicle_driver_assignments__drivers"`);
        await queryRunner.query(`ALTER TABLE "core"."vehicle_driver_assignments" DROP CONSTRAINT "FK__vehicle_driver_assignments__vehicles"`);
        await queryRunner.query(`ALTER TABLE "core"."drivers" DROP CONSTRAINT "FK__drivers__organizations"`);
        await queryRunner.query(`ALTER TABLE "core"."vehicles" DROP CONSTRAINT "FK__vehicles__fuel_types"`);
        await queryRunner.query(`ALTER TABLE "core"."vehicles" DROP CONSTRAINT "FK__vehicles__vehicle_brands"`);
        await queryRunner.query(`ALTER TABLE "core"."vehicles" DROP CONSTRAINT "FK__vehicles__vehicle_types"`);
        await queryRunner.query(`ALTER TABLE "core"."vehicles" DROP CONSTRAINT "FK__vehicles__organizations"`);
        await queryRunner.query(`DROP TABLE "core"."alerts"`);
        await queryRunner.query(`DROP TYPE "core"."alerts_severity_enum"`);
        await queryRunner.query(`DROP TYPE "core"."alerts_alert_type_enum"`);
        await queryRunner.query(`DROP TABLE "core"."gps_devices"`);
        await queryRunner.query(`DROP TABLE "core"."transportation_orders"`);
        await queryRunner.query(`DROP TYPE "core"."transportation_orders_priority_enum"`);
        await queryRunner.query(`DROP TYPE "core"."transportation_orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "core"."transportation_order_items"`);
        await queryRunner.query(`DROP TABLE "core"."vehicle_insurance"`);
        await queryRunner.query(`DROP TABLE "core"."driver_documents"`);
        await queryRunner.query(`DROP TYPE "core"."driver_documents_document_type_enum"`);
        await queryRunner.query(`DROP TABLE "core"."vehicle_documents"`);
        await queryRunner.query(`DROP TYPE "core"."vehicle_documents_document_type_enum"`);
        await queryRunner.query(`DROP TABLE "core"."vehicle_expenses"`);
        await queryRunner.query(`DROP TYPE "core"."vehicle_expenses_expense_type_enum"`);
        await queryRunner.query(`DROP TABLE "core"."maintenance_parts"`);
        await queryRunner.query(`DROP TABLE "core"."maintenance"`);
        await queryRunner.query(`DROP TYPE "core"."maintenance_status_enum"`);
        await queryRunner.query(`DROP TABLE "core"."maintenance_types"`);
        await queryRunner.query(`DROP TABLE "core"."fuel_transactions"`);
        await queryRunner.query(`DROP TABLE "core"."trip_events"`);
        await queryRunner.query(`DROP TYPE "core"."trip_events_event_type_enum"`);
        await queryRunner.query(`DROP TABLE "core"."trip_goods"`);
        await queryRunner.query(`DROP TABLE "core"."trip_checkpoints"`);
        await queryRunner.query(`DROP TABLE "core"."trips"`);
        await queryRunner.query(`DROP TYPE "core"."trips_trip_status_enum"`);
        await queryRunner.query(`DROP TABLE "core"."vehicle_locations"`);
        await queryRunner.query(`DROP TABLE "core"."vehicle_driver_assignments"`);
        await queryRunner.query(`DROP TABLE "core"."drivers"`);
        await queryRunner.query(`DROP TYPE "core"."drivers_status_enum"`);
        await queryRunner.query(`DROP TABLE "core"."vehicles"`);
        await queryRunner.query(`DROP TYPE "core"."vehicles_status_enum"`);
        await queryRunner.query(`DROP TABLE "core"."fuel_types"`);
        await queryRunner.query(`DROP TABLE "core"."vehicle_brands"`);
        await queryRunner.query(`DROP TABLE "core"."vehicle_types"`);
    }

}
