import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1800000000003 implements MigrationInterface {
    name = 'Migration1800000000003'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "core"."org_members" DROP CONSTRAINT "FK__org_members__organizations"`);
        await queryRunner.query(`ALTER TABLE "core"."org_members" DROP CONSTRAINT "FK__org_members__users"`);
        await queryRunner.query(`ALTER TABLE "core"."org_members" DROP CONSTRAINT "FK__org_members__invited_by"`);
        await queryRunner.query(`DROP INDEX "core"."IDX__users__clerk_user_id"`);
        await queryRunner.query(`DROP INDEX "core"."IDX__org_members__org_id"`);
        await queryRunner.query(`DROP INDEX "core"."IDX__org_members__user_id"`);
        await queryRunner.query(`ALTER TABLE "core"."org_members" DROP CONSTRAINT "UQ__org_members__org_user"`);
        await queryRunner.query(`CREATE TABLE "core"."product_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "storage_key" character varying(500) NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', "is_primary" boolean NOT NULL DEFAULT false, "uploaded_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_product_images" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."product_suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "supplier_id" uuid NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "unit_cost" numeric(18,4), "lead_time_days" integer, "min_order_qty" numeric(18,4), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_product_suppliers" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ__product_suppliers__product_supplier" ON "core"."product_suppliers" ("product_id", "supplier_id") `);
        await queryRunner.query(`CREATE TABLE "core"."customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "email" character varying(255), "phone" character varying(20), "gstin" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_customers" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."discount_coupons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "org_id" uuid NOT NULL, "code" character varying(50) NOT NULL, "type" character varying(20) NOT NULL DEFAULT 'percentage', "value" numeric(18,4) NOT NULL, "max_uses" integer, "used_count" integer NOT NULL DEFAULT '0', "valid_from" TIMESTAMP, "valid_until" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_discount_coupons" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7e3ce2a9666b36fb7d96d975ba" ON "core"."discount_coupons" ("org_id", "code") `);
        await queryRunner.query(`CREATE TABLE "core"."order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "product_id" uuid NOT NULL, "variant_id" uuid, "quantity" numeric(18,4) NOT NULL, "unit_price" numeric(18,4) NOT NULL, "tax_amount" numeric(18,4) NOT NULL DEFAULT '0', "line_total" numeric(18,4) NOT NULL, CONSTRAINT "PK_order_items" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_number" character varying(50) NOT NULL, "store_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'PENDING', "subtotal" numeric(18,4) NOT NULL DEFAULT '0', "tax_amount" numeric(18,4) NOT NULL DEFAULT '0', "total_amount" numeric(18,4) NOT NULL DEFAULT '0', "payment_status" character varying(50) NOT NULL DEFAULT 'UNPAID', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_75eba1c6b1a66b09f2a97e6927b" UNIQUE ("order_number"), CONSTRAINT "PK_orders" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "invoice_number" character varying(50) NOT NULL, "total_amount" numeric(18,4) NOT NULL DEFAULT '0', "status" character varying(50) NOT NULL DEFAULT 'DRAFT', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_invoices" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."bills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid NOT NULL, "store_id" uuid NOT NULL, "total_amount" numeric(18,4) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_bills" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."payment_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "org_id" uuid NOT NULL, "reference_id" uuid NOT NULL, "reference_type" character varying(50) NOT NULL, "type" character varying(50) NOT NULL, "method" character varying(50) NOT NULL, "amount" numeric(18,4) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_payment_transactions" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "org_id" uuid NOT NULL, "store_id" uuid, "category" character varying(50) NOT NULL, "amount" numeric(18,4) NOT NULL DEFAULT '0', "expense_date" TIMESTAMP NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_expenses" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."return_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "return_id" uuid NOT NULL, "product_id" uuid NOT NULL, "variant_id" uuid, "quantity" numeric(18,4) NOT NULL, CONSTRAINT "PK_return_items" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."item_returns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "store_id" uuid NOT NULL, "order_id" uuid, "supplier_id" uuid, "return_type" character varying(50) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "total_amount" numeric(18,4) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "PK_item_returns" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "org_id" uuid NOT NULL, "type" character varying(50) NOT NULL, "title" character varying(255) NOT NULL, "body" text NOT NULL, "read_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_notifications" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."org_activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "org_id" uuid NOT NULL, "actor_id" uuid, "event_type" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_org_activity_logs" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."report_generation_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "org_id" uuid NOT NULL, "report_type" character varying(100) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'pending', "file_url" character varying(255), "error_message" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_report_generation_logs" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."stock_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "store_id" uuid NOT NULL, "product_id" uuid NOT NULL, "supplier_id" uuid, "quantity" numeric(18,4) NOT NULL, "unit_cost" numeric(18,4) NOT NULL DEFAULT '0', "entry_type" character varying(50) NOT NULL DEFAULT 'purchase', "reference_number" character varying(100), "status" character varying(50) NOT NULL DEFAULT 'completed', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_stock_entries" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."stock_transfer_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transfer_id" uuid NOT NULL, "product_id" uuid NOT NULL, "variant_id" uuid, "quantity_sent" numeric(18,4) NOT NULL, "quantity_received" numeric(18,4) NOT NULL DEFAULT '0', CONSTRAINT "PK_stock_transfer_items" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."stock_transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "from_store_id" uuid NOT NULL, "to_store_id" uuid NOT NULL, "transfer_number" character varying(50) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'PENDING', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_e6943db71fc295dca9bbe16b85c" UNIQUE ("transfer_number"), CONSTRAINT "PK_stock_transfers" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."store_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "store_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'active', CONSTRAINT "PK_store_members" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e119dedd3232bbe7db331e0673" ON "core"."store_members" ("store_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "core"."product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "sku" character varying(100) NOT NULL, "attributes" jsonb, "unit_price" numeric(18,4) NOT NULL DEFAULT '0', "cost_price" numeric(18,4) NOT NULL DEFAULT '0', CONSTRAINT "PK_product_variants" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ceaa413b9fe3dbfd6e889dc5a7" ON "core"."product_variants" ("product_id", "sku") `);
        await queryRunner.query(`CREATE TABLE "core"."store_product_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "store_id" uuid NOT NULL, "product_id" uuid NOT NULL, "variant_id" uuid, "selling_price" numeric(18,4) NOT NULL DEFAULT '0', "min_stock_level" integer NOT NULL DEFAULT '0', "is_available" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_store_product_config" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_39dcd19902940897f3e545ba8d" ON "core"."store_product_config" ("store_id", "product_id", "variant_id") `);
        await queryRunner.query(`CREATE TABLE "core"."user_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "first_name" character varying(255) NOT NULL, "last_name" character varying(255) NOT NULL, "avatar_url" character varying(255), "timezone" character varying(50) NOT NULL DEFAULT 'UTC', "locale" character varying(10) NOT NULL DEFAULT 'en', CONSTRAINT "UQ_6ca9503d77ae39b4b5a6cc3ba88" UNIQUE ("user_id"), CONSTRAINT "REL_6ca9503d77ae39b4b5a6cc3ba8" UNIQUE ("user_id"), CONSTRAINT "PK_user_profiles" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."user_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" character varying(50) NOT NULL DEFAULT 'home', "line1" character varying(255) NOT NULL, "line2" character varying(255), "city" character varying(100) NOT NULL, "state" character varying(100), "country" character varying(100) NOT NULL, "postal_code" character varying(20) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_user_addresses" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "resource" character varying(100) NOT NULL, "action" character varying(50) NOT NULL, CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_permissions" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."platforms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "config" jsonb, "maintenance_mode" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_platforms" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."platform_configurations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "config_key" character varying(100) NOT NULL, "config_value" jsonb, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_d0ac8bfebcdb32c2e6d0a16e7ca" UNIQUE ("config_key"), CONSTRAINT "PK_platform_configurations" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "selling_price"`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "retail_price" numeric(18,4) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "loyalty_price" numeric(18,4) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "wholesale_price" numeric(18,4) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "transfer_price" numeric(18,4) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_986db88b0e82a9189921841199" ON "core"."org_members" ("org_id", "user_id") `);
        await queryRunner.query(`ALTER TABLE "core"."product_images" ADD CONSTRAINT "FK__product_images__products" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."product_images" ADD CONSTRAINT "FK__product_images__users" FOREIGN KEY ("uploaded_by_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."product_suppliers" ADD CONSTRAINT "FK__product_suppliers__products" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."product_suppliers" ADD CONSTRAINT "FK__product_suppliers__suppliers" FOREIGN KEY ("supplier_id") REFERENCES "core"."suppliers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD CONSTRAINT "FK__products__users" FOREIGN KEY ("created_by_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."customers" ADD CONSTRAINT "FK__customers__organizations" FOREIGN KEY ("organization_id") REFERENCES "core"."organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."discount_coupons" ADD CONSTRAINT "FK__discount_coupons__organizations" FOREIGN KEY ("org_id") REFERENCES "core"."organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."order_items" ADD CONSTRAINT "FK__order_items__orders" FOREIGN KEY ("order_id") REFERENCES "core"."orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."order_items" ADD CONSTRAINT "FK__order_items__products" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."orders" ADD CONSTRAINT "FK__orders__stores" FOREIGN KEY ("store_id") REFERENCES "core"."stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."orders" ADD CONSTRAINT "FK__orders__customers" FOREIGN KEY ("customer_id") REFERENCES "core"."customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."invoices" ADD CONSTRAINT "FK__invoices__orders" FOREIGN KEY ("order_id") REFERENCES "core"."orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."bills" ADD CONSTRAINT "FK__bills__suppliers" FOREIGN KEY ("supplier_id") REFERENCES "core"."suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."bills" ADD CONSTRAINT "FK__bills__stores" FOREIGN KEY ("store_id") REFERENCES "core"."stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."payment_transactions" ADD CONSTRAINT "FK__payment_transactions__organizations" FOREIGN KEY ("org_id") REFERENCES "core"."organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."expenses" ADD CONSTRAINT "FK__expenses__organizations" FOREIGN KEY ("org_id") REFERENCES "core"."organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."expenses" ADD CONSTRAINT "FK__expenses__stores" FOREIGN KEY ("store_id") REFERENCES "core"."stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."return_items" ADD CONSTRAINT "FK__return_items__item_returns" FOREIGN KEY ("return_id") REFERENCES "core"."item_returns"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."return_items" ADD CONSTRAINT "FK__return_items__products" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."item_returns" ADD CONSTRAINT "FK__item_returns__stores" FOREIGN KEY ("store_id") REFERENCES "core"."stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."item_returns" ADD CONSTRAINT "FK__item_returns__orders" FOREIGN KEY ("order_id") REFERENCES "core"."orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."item_returns" ADD CONSTRAINT "FK__item_returns__suppliers" FOREIGN KEY ("supplier_id") REFERENCES "core"."suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."notifications" ADD CONSTRAINT "FK__notifications__users" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."notifications" ADD CONSTRAINT "FK__notifications__organizations" FOREIGN KEY ("org_id") REFERENCES "core"."organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."org_activity_logs" ADD CONSTRAINT "FK__org_activity_logs__organizations" FOREIGN KEY ("org_id") REFERENCES "core"."organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."org_activity_logs" ADD CONSTRAINT "FK__org_activity_logs__actor" FOREIGN KEY ("actor_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."report_generation_logs" ADD CONSTRAINT "FK__report_generation_logs__organizations" FOREIGN KEY ("org_id") REFERENCES "core"."organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."stock_entries" ADD CONSTRAINT "FK__stock_entries__stores" FOREIGN KEY ("store_id") REFERENCES "core"."stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."stock_entries" ADD CONSTRAINT "FK__stock_entries__products" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."stock_entries" ADD CONSTRAINT "FK__stock_entries__suppliers" FOREIGN KEY ("supplier_id") REFERENCES "core"."suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."stock_transfer_items" ADD CONSTRAINT "FK__stock_transfer_items__stock_transfers" FOREIGN KEY ("transfer_id") REFERENCES "core"."stock_transfers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."stock_transfer_items" ADD CONSTRAINT "FK__stock_transfer_items__products" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."stock_transfers" ADD CONSTRAINT "FK__stock_transfers__organizations" FOREIGN KEY ("organization_id") REFERENCES "core"."organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."stock_transfers" ADD CONSTRAINT "FK__stock_transfers__from_stores" FOREIGN KEY ("from_store_id") REFERENCES "core"."stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."stock_transfers" ADD CONSTRAINT "FK__stock_transfers__to_stores" FOREIGN KEY ("to_store_id") REFERENCES "core"."stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."store_members" ADD CONSTRAINT "FK__store_members__stores" FOREIGN KEY ("store_id") REFERENCES "core"."stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."store_members" ADD CONSTRAINT "FK__store_members__users" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."store_members" ADD CONSTRAINT "FK__store_members__roles" FOREIGN KEY ("role_id") REFERENCES "core"."roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."product_variants" ADD CONSTRAINT "FK__product_variants__products" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."store_product_config" ADD CONSTRAINT "FK__store_product_config__stores" FOREIGN KEY ("store_id") REFERENCES "core"."stores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."store_product_config" ADD CONSTRAINT "FK__store_product_config__products" FOREIGN KEY ("product_id") REFERENCES "core"."products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."store_product_config" ADD CONSTRAINT "FK__store_product_config__product_variants" FOREIGN KEY ("variant_id") REFERENCES "core"."product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."user_profiles" ADD CONSTRAINT "FK__user_profiles__users" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."user_addresses" ADD CONSTRAINT "FK__user_addresses__users" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."role_permissions" ADD CONSTRAINT "FK__role_permissions__roles" FOREIGN KEY ("role_id") REFERENCES "core"."roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."role_permissions" ADD CONSTRAINT "FK__role_permissions__permissions" FOREIGN KEY ("permission_id") REFERENCES "core"."permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."org_members" ADD CONSTRAINT "FK__org_members__organizations" FOREIGN KEY ("org_id") REFERENCES "core"."organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."org_members" ADD CONSTRAINT "FK__org_members__users" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."org_members" ADD CONSTRAINT "FK__org_members__invited_by" FOREIGN KEY ("invited_by") REFERENCES "core"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "core"."org_members" DROP CONSTRAINT "FK__org_members__invited_by"`);
        await queryRunner.query(`ALTER TABLE "core"."org_members" DROP CONSTRAINT "FK__org_members__users"`);
        await queryRunner.query(`ALTER TABLE "core"."org_members" DROP CONSTRAINT "FK__org_members__organizations"`);
        await queryRunner.query(`ALTER TABLE "core"."role_permissions" DROP CONSTRAINT "FK__role_permissions__permissions"`);
        await queryRunner.query(`ALTER TABLE "core"."role_permissions" DROP CONSTRAINT "FK__role_permissions__roles"`);
        await queryRunner.query(`ALTER TABLE "core"."user_addresses" DROP CONSTRAINT "FK__user_addresses__users"`);
        await queryRunner.query(`ALTER TABLE "core"."user_profiles" DROP CONSTRAINT "FK__user_profiles__users"`);
        await queryRunner.query(`ALTER TABLE "core"."store_product_config" DROP CONSTRAINT "FK__store_product_config__product_variants"`);
        await queryRunner.query(`ALTER TABLE "core"."store_product_config" DROP CONSTRAINT "FK__store_product_config__products"`);
        await queryRunner.query(`ALTER TABLE "core"."store_product_config" DROP CONSTRAINT "FK__store_product_config__stores"`);
        await queryRunner.query(`ALTER TABLE "core"."product_variants" DROP CONSTRAINT "FK__product_variants__products"`);
        await queryRunner.query(`ALTER TABLE "core"."store_members" DROP CONSTRAINT "FK__store_members__roles"`);
        await queryRunner.query(`ALTER TABLE "core"."store_members" DROP CONSTRAINT "FK__store_members__users"`);
        await queryRunner.query(`ALTER TABLE "core"."store_members" DROP CONSTRAINT "FK__store_members__stores"`);
        await queryRunner.query(`ALTER TABLE "core"."stock_transfers" DROP CONSTRAINT "FK__stock_transfers__to_stores"`);
        await queryRunner.query(`ALTER TABLE "core"."stock_transfers" DROP CONSTRAINT "FK__stock_transfers__from_stores"`);
        await queryRunner.query(`ALTER TABLE "core"."stock_transfers" DROP CONSTRAINT "FK__stock_transfers__organizations"`);
        await queryRunner.query(`ALTER TABLE "core"."stock_transfer_items" DROP CONSTRAINT "FK__stock_transfer_items__products"`);
        await queryRunner.query(`ALTER TABLE "core"."stock_transfer_items" DROP CONSTRAINT "FK__stock_transfer_items__stock_transfers"`);
        await queryRunner.query(`ALTER TABLE "core"."stock_entries" DROP CONSTRAINT "FK__stock_entries__suppliers"`);
        await queryRunner.query(`ALTER TABLE "core"."stock_entries" DROP CONSTRAINT "FK__stock_entries__products"`);
        await queryRunner.query(`ALTER TABLE "core"."stock_entries" DROP CONSTRAINT "FK__stock_entries__stores"`);
        await queryRunner.query(`ALTER TABLE "core"."report_generation_logs" DROP CONSTRAINT "FK__report_generation_logs__organizations"`);
        await queryRunner.query(`ALTER TABLE "core"."org_activity_logs" DROP CONSTRAINT "FK__org_activity_logs__actor"`);
        await queryRunner.query(`ALTER TABLE "core"."org_activity_logs" DROP CONSTRAINT "FK__org_activity_logs__organizations"`);
        await queryRunner.query(`ALTER TABLE "core"."notifications" DROP CONSTRAINT "FK__notifications__organizations"`);
        await queryRunner.query(`ALTER TABLE "core"."notifications" DROP CONSTRAINT "FK__notifications__users"`);
        await queryRunner.query(`ALTER TABLE "core"."item_returns" DROP CONSTRAINT "FK__item_returns__suppliers"`);
        await queryRunner.query(`ALTER TABLE "core"."item_returns" DROP CONSTRAINT "FK__item_returns__orders"`);
        await queryRunner.query(`ALTER TABLE "core"."item_returns" DROP CONSTRAINT "FK__item_returns__stores"`);
        await queryRunner.query(`ALTER TABLE "core"."return_items" DROP CONSTRAINT "FK__return_items__products"`);
        await queryRunner.query(`ALTER TABLE "core"."return_items" DROP CONSTRAINT "FK__return_items__item_returns"`);
        await queryRunner.query(`ALTER TABLE "core"."expenses" DROP CONSTRAINT "FK__expenses__stores"`);
        await queryRunner.query(`ALTER TABLE "core"."expenses" DROP CONSTRAINT "FK__expenses__organizations"`);
        await queryRunner.query(`ALTER TABLE "core"."payment_transactions" DROP CONSTRAINT "FK__payment_transactions__organizations"`);
        await queryRunner.query(`ALTER TABLE "core"."bills" DROP CONSTRAINT "FK__bills__stores"`);
        await queryRunner.query(`ALTER TABLE "core"."bills" DROP CONSTRAINT "FK__bills__suppliers"`);
        await queryRunner.query(`ALTER TABLE "core"."invoices" DROP CONSTRAINT "FK__invoices__orders"`);
        await queryRunner.query(`ALTER TABLE "core"."orders" DROP CONSTRAINT "FK__orders__customers"`);
        await queryRunner.query(`ALTER TABLE "core"."orders" DROP CONSTRAINT "FK__orders__stores"`);
        await queryRunner.query(`ALTER TABLE "core"."order_items" DROP CONSTRAINT "FK__order_items__products"`);
        await queryRunner.query(`ALTER TABLE "core"."order_items" DROP CONSTRAINT "FK__order_items__orders"`);
        await queryRunner.query(`ALTER TABLE "core"."discount_coupons" DROP CONSTRAINT "FK__discount_coupons__organizations"`);
        await queryRunner.query(`ALTER TABLE "core"."customers" DROP CONSTRAINT "FK__customers__organizations"`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP CONSTRAINT "FK__products__users"`);
        await queryRunner.query(`ALTER TABLE "core"."product_suppliers" DROP CONSTRAINT "FK__product_suppliers__suppliers"`);
        await queryRunner.query(`ALTER TABLE "core"."product_suppliers" DROP CONSTRAINT "FK__product_suppliers__products"`);
        await queryRunner.query(`ALTER TABLE "core"."product_images" DROP CONSTRAINT "FK__product_images__users"`);
        await queryRunner.query(`ALTER TABLE "core"."product_images" DROP CONSTRAINT "FK__product_images__products"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_986db88b0e82a9189921841199"`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "transfer_price"`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "wholesale_price"`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "loyalty_price"`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "retail_price"`);
        await queryRunner.query(`ALTER TABLE "core"."products" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "image_url" text`);
        await queryRunner.query(`ALTER TABLE "core"."products" ADD "selling_price" numeric(18,4) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP TABLE "core"."platform_configurations"`);
        await queryRunner.query(`DROP TABLE "core"."platforms"`);
        await queryRunner.query(`DROP TABLE "core"."role_permissions"`);
        await queryRunner.query(`DROP TABLE "core"."permissions"`);
        await queryRunner.query(`DROP TABLE "core"."user_addresses"`);
        await queryRunner.query(`DROP TABLE "core"."user_profiles"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_39dcd19902940897f3e545ba8d"`);
        await queryRunner.query(`DROP TABLE "core"."store_product_config"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_ceaa413b9fe3dbfd6e889dc5a7"`);
        await queryRunner.query(`DROP TABLE "core"."product_variants"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_e119dedd3232bbe7db331e0673"`);
        await queryRunner.query(`DROP TABLE "core"."store_members"`);
        await queryRunner.query(`DROP TABLE "core"."stock_transfers"`);
        await queryRunner.query(`DROP TABLE "core"."stock_transfer_items"`);
        await queryRunner.query(`DROP TABLE "core"."stock_entries"`);
        await queryRunner.query(`DROP TABLE "core"."report_generation_logs"`);
        await queryRunner.query(`DROP TABLE "core"."org_activity_logs"`);
        await queryRunner.query(`DROP TABLE "core"."notifications"`);
        await queryRunner.query(`DROP TABLE "core"."item_returns"`);
        await queryRunner.query(`DROP TABLE "core"."return_items"`);
        await queryRunner.query(`DROP TABLE "core"."expenses"`);
        await queryRunner.query(`DROP TABLE "core"."payment_transactions"`);
        await queryRunner.query(`DROP TABLE "core"."bills"`);
        await queryRunner.query(`DROP TABLE "core"."invoices"`);
        await queryRunner.query(`DROP TABLE "core"."orders"`);
        await queryRunner.query(`DROP TABLE "core"."order_items"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_7e3ce2a9666b36fb7d96d975ba"`);
        await queryRunner.query(`DROP TABLE "core"."discount_coupons"`);
        await queryRunner.query(`DROP TABLE "core"."customers"`);
        await queryRunner.query(`DROP INDEX "core"."UQ__product_suppliers__product_supplier"`);
        await queryRunner.query(`DROP TABLE "core"."product_suppliers"`);
        await queryRunner.query(`DROP TABLE "core"."product_images"`);
        await queryRunner.query(`ALTER TABLE "core"."org_members" ADD CONSTRAINT "UQ__org_members__org_user" UNIQUE ("org_id", "user_id")`);
        await queryRunner.query(`CREATE INDEX "IDX__org_members__user_id" ON "core"."org_members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX__org_members__org_id" ON "core"."org_members" ("org_id") `);
        await queryRunner.query(`CREATE INDEX "IDX__users__clerk_user_id" ON "core"."users" ("clerk_user_id") `);
        await queryRunner.query(`ALTER TABLE "core"."org_members" ADD CONSTRAINT "FK__org_members__invited_by" FOREIGN KEY ("invited_by") REFERENCES "core"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."org_members" ADD CONSTRAINT "FK__org_members__users" FOREIGN KEY ("user_id") REFERENCES "core"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."org_members" ADD CONSTRAINT "FK__org_members__organizations" FOREIGN KEY ("org_id") REFERENCES "core"."organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
