import { ApiPropertyOptional } from '@nestjs/swagger';
import { IsEmail, IsOptional, IsString } from 'class-validator';

export class SendQuotationEmailDto {
  @ApiPropertyOptional({ description: 'Recipient email address. If omitted, uses customer email on file.' })
  @IsEmail()
  @IsOptional()
  public recipientEmail?: string;

  @ApiPropertyOptional({ description: 'Email subject. If omitted, a default subject is generated.' })
  @IsString()
  @IsOptional()
  public subject?: string;

  @ApiPropertyOptional({ description: 'Email body HTML or text. If omitted, a default quotation email is generated.' })
  @IsString()
  @IsOptional()
  public body?: string;

  @ApiPropertyOptional({ description: 'Base64-encoded PDF generated by Electron desktop client. If omitted, backend generates PDF.' })
  @IsString()
  @IsOptional()
  public pdfBase64?: string;
}
