import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsEmail, IsNotEmpty, IsOptional, IsString } from 'class-validator';

export class SendQuotationEmailDto {
  @ApiProperty({ description: 'Recipient email address' })
  @IsEmail()
  @IsNotEmpty()
  public recipientEmail: string;

  @ApiProperty({ description: 'Email subject' })
  @IsString()
  @IsNotEmpty()
  public subject: string;

  @ApiProperty({ description: 'Email body HTML or text' })
  @IsString()
  @IsNotEmpty()
  public body: string;

  @ApiPropertyOptional({ description: 'Base64-encoded PDF generated by Electron desktop client' })
  @IsString()
  @IsOptional()
  public pdfBase64?: string;
}
