import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { InjectPinoLogger, PinoLogger } from "nestjs-pino";
import { FindOptionsWhere, Repository, DataSource } from "typeorm";
import { BaseSeed } from "../../../common";
import { CountryEntity } from "../entities";

@Injectable()
export class RefCountriesSeed extends BaseSeed<CountryEntity> {
  public get version(): number { return 1; }
  public get seedingData(): Partial<CountryEntity>[] {
    return [
  {
    "id": 1,
    "name": "Afghanistan",
    "iso3": "AFG",
    "iso2": "AF",
    "phoneCode": "93",
    "currency": "AFN",
    "currencySymbol": "؋",
    "native": "افغانستان",
    "region": "Asia",
    "latitude": 33,
    "longitude": 65
  },
  {
    "id": 2,
    "name": "Aland Islands",
    "iso3": "ALA",
    "iso2": "AX",
    "phoneCode": "+358-18",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Åland",
    "region": "Europe",
    "latitude": 60.116667,
    "longitude": 19.9
  },
  {
    "id": 3,
    "name": "Albania",
    "iso3": "ALB",
    "iso2": "AL",
    "phoneCode": "355",
    "currency": "ALL",
    "currencySymbol": "Lek",
    "native": "Shqipëria",
    "region": "Europe",
    "latitude": 41,
    "longitude": 20
  },
  {
    "id": 4,
    "name": "Algeria",
    "iso3": "DZA",
    "iso2": "DZ",
    "phoneCode": "213",
    "currency": "DZD",
    "currencySymbol": "دج",
    "native": "الجزائر",
    "region": "Africa",
    "latitude": 28,
    "longitude": 3
  },
  {
    "id": 5,
    "name": "American Samoa",
    "iso3": "ASM",
    "iso2": "AS",
    "phoneCode": "+1-684",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "American Samoa",
    "region": "Oceania",
    "latitude": -14.33333333,
    "longitude": -170
  },
  {
    "id": 6,
    "name": "Andorra",
    "iso3": "AND",
    "iso2": "AD",
    "phoneCode": "376",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Andorra",
    "region": "Europe",
    "latitude": 42.5,
    "longitude": 1.5
  },
  {
    "id": 7,
    "name": "Angola",
    "iso3": "AGO",
    "iso2": "AO",
    "phoneCode": "244",
    "currency": "AOA",
    "currencySymbol": "Kz",
    "native": "Angola",
    "region": "Africa",
    "latitude": -12.5,
    "longitude": 18.5
  },
  {
    "id": 8,
    "name": "Anguilla",
    "iso3": "AIA",
    "iso2": "AI",
    "phoneCode": "+1-264",
    "currency": "XCD",
    "currencySymbol": "$",
    "native": "Anguilla",
    "region": "Americas",
    "latitude": 18.25,
    "longitude": -63.16666666
  },
  {
    "id": 9,
    "name": "Antarctica",
    "iso3": "ATA",
    "iso2": "AQ",
    "currency": "",
    "currencySymbol": "$",
    "native": "Antarctica",
    "region": "Polar",
    "latitude": -74.65,
    "longitude": 4.48
  },
  {
    "id": 10,
    "name": "Antigua And Barbuda",
    "iso3": "ATG",
    "iso2": "AG",
    "phoneCode": "+1-268",
    "currency": "XCD",
    "currencySymbol": "$",
    "native": "Antigua and Barbuda",
    "region": "Americas",
    "latitude": 17.05,
    "longitude": -61.8
  },
  {
    "id": 11,
    "name": "Argentina",
    "iso3": "ARG",
    "iso2": "AR",
    "phoneCode": "54",
    "currency": "ARS",
    "currencySymbol": "$",
    "native": "Argentina",
    "region": "Americas",
    "latitude": -34,
    "longitude": -64
  },
  {
    "id": 12,
    "name": "Armenia",
    "iso3": "ARM",
    "iso2": "AM",
    "phoneCode": "374",
    "currency": "AMD",
    "currencySymbol": "֏",
    "native": "Հայաստան",
    "region": "Asia",
    "latitude": 40,
    "longitude": 45
  },
  {
    "id": 13,
    "name": "Aruba",
    "iso3": "ABW",
    "iso2": "AW",
    "phoneCode": "297",
    "currency": "AWG",
    "currencySymbol": "ƒ",
    "native": "Aruba",
    "region": "Americas",
    "latitude": 12.5,
    "longitude": -69.96666666
  },
  {
    "id": 14,
    "name": "Australia",
    "iso3": "AUS",
    "iso2": "AU",
    "phoneCode": "61",
    "currency": "AUD",
    "currencySymbol": "$",
    "native": "Australia",
    "region": "Oceania",
    "latitude": -27,
    "longitude": 133
  },
  {
    "id": 15,
    "name": "Austria",
    "iso3": "AUT",
    "iso2": "AT",
    "phoneCode": "43",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Österreich",
    "region": "Europe",
    "latitude": 47.33333333,
    "longitude": 13.33333333
  },
  {
    "id": 16,
    "name": "Azerbaijan",
    "iso3": "AZE",
    "iso2": "AZ",
    "phoneCode": "994",
    "currency": "AZN",
    "currencySymbol": "m",
    "native": "Azərbaycan",
    "region": "Asia",
    "latitude": 40.5,
    "longitude": 47.5
  },
  {
    "id": 17,
    "name": "Bahamas The",
    "iso3": "BHS",
    "iso2": "BS",
    "phoneCode": "+1-242",
    "currency": "BSD",
    "currencySymbol": "B$",
    "native": "Bahamas",
    "region": "Americas",
    "latitude": 24.25,
    "longitude": -76
  },
  {
    "id": 18,
    "name": "Bahrain",
    "iso3": "BHR",
    "iso2": "BH",
    "phoneCode": "973",
    "currency": "BHD",
    "currencySymbol": ".د.ب",
    "native": "‏البحرين",
    "region": "Asia",
    "latitude": 26,
    "longitude": 50.55
  },
  {
    "id": 19,
    "name": "Bangladesh",
    "iso3": "BGD",
    "iso2": "BD",
    "phoneCode": "880",
    "currency": "BDT",
    "currencySymbol": "৳",
    "native": "Bangladesh",
    "region": "Asia",
    "latitude": 24,
    "longitude": 90
  },
  {
    "id": 20,
    "name": "Barbados",
    "iso3": "BRB",
    "iso2": "BB",
    "phoneCode": "+1-246",
    "currency": "BBD",
    "currencySymbol": "Bds$",
    "native": "Barbados",
    "region": "Americas",
    "latitude": 13.16666666,
    "longitude": -59.53333333
  },
  {
    "id": 21,
    "name": "Belarus",
    "iso3": "BLR",
    "iso2": "BY",
    "phoneCode": "375",
    "currency": "BYN",
    "currencySymbol": "Br",
    "native": "Белару́сь",
    "region": "Europe",
    "latitude": 53,
    "longitude": 28
  },
  {
    "id": 22,
    "name": "Belgium",
    "iso3": "BEL",
    "iso2": "BE",
    "phoneCode": "32",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "België",
    "region": "Europe",
    "latitude": 50.83333333,
    "longitude": 4
  },
  {
    "id": 23,
    "name": "Belize",
    "iso3": "BLZ",
    "iso2": "BZ",
    "phoneCode": "501",
    "currency": "BZD",
    "currencySymbol": "$",
    "native": "Belize",
    "region": "Americas",
    "latitude": 17.25,
    "longitude": -88.75
  },
  {
    "id": 24,
    "name": "Benin",
    "iso3": "BEN",
    "iso2": "BJ",
    "phoneCode": "229",
    "currency": "XOF",
    "currencySymbol": "CFA",
    "native": "Bénin",
    "region": "Africa",
    "latitude": 9.5,
    "longitude": 2.25
  },
  {
    "id": 25,
    "name": "Bermuda",
    "iso3": "BMU",
    "iso2": "BM",
    "phoneCode": "+1-441",
    "currency": "BMD",
    "currencySymbol": "$",
    "native": "Bermuda",
    "region": "Americas",
    "latitude": 32.33333333,
    "longitude": -64.75
  },
  {
    "id": 26,
    "name": "Bhutan",
    "iso3": "BTN",
    "iso2": "BT",
    "phoneCode": "975",
    "currency": "BTN",
    "currencySymbol": "Nu.",
    "native": "ʼbrug-yul",
    "region": "Asia",
    "latitude": 27.5,
    "longitude": 90.5
  },
  {
    "id": 27,
    "name": "Bolivia",
    "iso3": "BOL",
    "iso2": "BO",
    "phoneCode": "591",
    "currency": "BOB",
    "currencySymbol": "Bs.",
    "native": "Bolivia",
    "region": "Americas",
    "latitude": -17,
    "longitude": -65
  },
  {
    "id": 28,
    "name": "Bosnia and Herzegovina",
    "iso3": "BIH",
    "iso2": "BA",
    "phoneCode": "387",
    "currency": "BAM",
    "currencySymbol": "KM",
    "native": "Bosna i Hercegovina",
    "region": "Europe",
    "latitude": 44,
    "longitude": 18
  },
  {
    "id": 29,
    "name": "Botswana",
    "iso3": "BWA",
    "iso2": "BW",
    "phoneCode": "267",
    "currency": "BWP",
    "currencySymbol": "P",
    "native": "Botswana",
    "region": "Africa",
    "latitude": -22,
    "longitude": 24
  },
  {
    "id": 30,
    "name": "Bouvet Island",
    "iso3": "BVT",
    "iso2": "BV",
    "phoneCode": "0055",
    "currency": "NOK",
    "currencySymbol": "kr",
    "native": "Bouvetøya",
    "region": "",
    "latitude": -54.43333333,
    "longitude": 3.4
  },
  {
    "id": 31,
    "name": "Brazil",
    "iso3": "BRA",
    "iso2": "BR",
    "phoneCode": "55",
    "currency": "BRL",
    "currencySymbol": "R$",
    "native": "Brasil",
    "region": "Americas",
    "latitude": -10,
    "longitude": -55
  },
  {
    "id": 32,
    "name": "British Indian Ocean Territory",
    "iso3": "IOT",
    "iso2": "IO",
    "phoneCode": "246",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "British Indian Ocean Territory",
    "region": "Africa",
    "latitude": -6,
    "longitude": 71.5
  },
  {
    "id": 33,
    "name": "Brunei",
    "iso3": "BRN",
    "iso2": "BN",
    "phoneCode": "673",
    "currency": "BND",
    "currencySymbol": "B$",
    "native": "Negara Brunei Darussalam",
    "region": "Asia",
    "latitude": 4.5,
    "longitude": 114.66666666
  },
  {
    "id": 34,
    "name": "Bulgaria",
    "iso3": "BGR",
    "iso2": "BG",
    "phoneCode": "359",
    "currency": "BGN",
    "currencySymbol": "Лв.",
    "native": "България",
    "region": "Europe",
    "latitude": 43,
    "longitude": 25
  },
  {
    "id": 35,
    "name": "Burkina Faso",
    "iso3": "BFA",
    "iso2": "BF",
    "phoneCode": "226",
    "currency": "XOF",
    "currencySymbol": "CFA",
    "native": "Burkina Faso",
    "region": "Africa",
    "latitude": 13,
    "longitude": -2
  },
  {
    "id": 36,
    "name": "Burundi",
    "iso3": "BDI",
    "iso2": "BI",
    "phoneCode": "257",
    "currency": "BIF",
    "currencySymbol": "FBu",
    "native": "Burundi",
    "region": "Africa",
    "latitude": -3.5,
    "longitude": 30
  },
  {
    "id": 37,
    "name": "Cambodia",
    "iso3": "KHM",
    "iso2": "KH",
    "phoneCode": "855",
    "currency": "KHR",
    "currencySymbol": "KHR",
    "native": "Kâmpŭchéa",
    "region": "Asia",
    "latitude": 13,
    "longitude": 105
  },
  {
    "id": 38,
    "name": "Cameroon",
    "iso3": "CMR",
    "iso2": "CM",
    "phoneCode": "237",
    "currency": "XAF",
    "currencySymbol": "FCFA",
    "native": "Cameroon",
    "region": "Africa",
    "latitude": 6,
    "longitude": 12
  },
  {
    "id": 39,
    "name": "Canada",
    "iso3": "CAN",
    "iso2": "CA",
    "phoneCode": "1",
    "currency": "CAD",
    "currencySymbol": "$",
    "native": "Canada",
    "region": "Americas",
    "latitude": 60,
    "longitude": -95
  },
  {
    "id": 40,
    "name": "Cape Verde",
    "iso3": "CPV",
    "iso2": "CV",
    "phoneCode": "238",
    "currency": "CVE",
    "currencySymbol": "$",
    "native": "Cabo Verde",
    "region": "Africa",
    "latitude": 16,
    "longitude": -24
  },
  {
    "id": 41,
    "name": "Cayman Islands",
    "iso3": "CYM",
    "iso2": "KY",
    "phoneCode": "+1-345",
    "currency": "KYD",
    "currencySymbol": "$",
    "native": "Cayman Islands",
    "region": "Americas",
    "latitude": 19.5,
    "longitude": -80.5
  },
  {
    "id": 42,
    "name": "Central African Republic",
    "iso3": "CAF",
    "iso2": "CF",
    "phoneCode": "236",
    "currency": "XAF",
    "currencySymbol": "FCFA",
    "native": "Ködörösêse tî Bêafrîka",
    "region": "Africa",
    "latitude": 7,
    "longitude": 21
  },
  {
    "id": 43,
    "name": "Chad",
    "iso3": "TCD",
    "iso2": "TD",
    "phoneCode": "235",
    "currency": "XAF",
    "currencySymbol": "FCFA",
    "native": "Tchad",
    "region": "Africa",
    "latitude": 15,
    "longitude": 19
  },
  {
    "id": 44,
    "name": "Chile",
    "iso3": "CHL",
    "iso2": "CL",
    "phoneCode": "56",
    "currency": "CLP",
    "currencySymbol": "$",
    "native": "Chile",
    "region": "Americas",
    "latitude": -30,
    "longitude": -71
  },
  {
    "id": 45,
    "name": "China",
    "iso3": "CHN",
    "iso2": "CN",
    "phoneCode": "86",
    "currency": "CNY",
    "currencySymbol": "¥",
    "native": "中国",
    "region": "Asia",
    "latitude": 35,
    "longitude": 105
  },
  {
    "id": 46,
    "name": "Christmas Island",
    "iso3": "CXR",
    "iso2": "CX",
    "phoneCode": "61",
    "currency": "AUD",
    "currencySymbol": "$",
    "native": "Christmas Island",
    "region": "Oceania",
    "latitude": -10.5,
    "longitude": 105.66666666
  },
  {
    "id": 47,
    "name": "Cocos (Keeling) Islands",
    "iso3": "CCK",
    "iso2": "CC",
    "phoneCode": "61",
    "currency": "AUD",
    "currencySymbol": "$",
    "native": "Cocos (Keeling) Islands",
    "region": "Oceania",
    "latitude": -12.5,
    "longitude": 96.83333333
  },
  {
    "id": 48,
    "name": "Colombia",
    "iso3": "COL",
    "iso2": "CO",
    "phoneCode": "57",
    "currency": "COP",
    "currencySymbol": "$",
    "native": "Colombia",
    "region": "Americas",
    "latitude": 4,
    "longitude": -72
  },
  {
    "id": 49,
    "name": "Comoros",
    "iso3": "COM",
    "iso2": "KM",
    "phoneCode": "269",
    "currency": "KMF",
    "currencySymbol": "CF",
    "native": "Komori",
    "region": "Africa",
    "latitude": -12.16666666,
    "longitude": 44.25
  },
  {
    "id": 50,
    "name": "Congo",
    "iso3": "COG",
    "iso2": "CG",
    "phoneCode": "242",
    "currency": "XAF",
    "currencySymbol": "FC",
    "native": "République du Congo",
    "region": "Africa",
    "latitude": -1,
    "longitude": 15
  },
  {
    "id": 51,
    "name": "Congo The Democratic Republic Of The",
    "iso3": "COD",
    "iso2": "CD",
    "phoneCode": "243",
    "currency": "CDF",
    "currencySymbol": "FC",
    "native": "République démocratique du Congo",
    "region": "Africa",
    "latitude": 0,
    "longitude": 25
  },
  {
    "id": 52,
    "name": "Cook Islands",
    "iso3": "COK",
    "iso2": "CK",
    "phoneCode": "682",
    "currency": "NZD",
    "currencySymbol": "$",
    "native": "Cook Islands",
    "region": "Oceania",
    "latitude": -21.23333333,
    "longitude": -159.76666666
  },
  {
    "id": 53,
    "name": "Costa Rica",
    "iso3": "CRI",
    "iso2": "CR",
    "phoneCode": "506",
    "currency": "CRC",
    "currencySymbol": "₡",
    "native": "Costa Rica",
    "region": "Americas",
    "latitude": 10,
    "longitude": -84
  },
  {
    "id": 54,
    "name": "Cote D\"Ivoire (Ivory Coast)",
    "iso3": "CIV",
    "iso2": "CI",
    "phoneCode": "225",
    "currency": "XOF",
    "currencySymbol": "CFA",
    "native": null,
    "region": "Africa",
    "latitude": 8,
    "longitude": -5
  },
  {
    "id": 55,
    "name": "Croatia (Hrvatska)",
    "iso3": "HRV",
    "iso2": "HR",
    "phoneCode": "385",
    "currency": "HRK",
    "currencySymbol": "kn",
    "native": "Hrvatska",
    "region": "Europe",
    "latitude": 45.16666666,
    "longitude": 15.5
  },
  {
    "id": 56,
    "name": "Cuba",
    "iso3": "CUB",
    "iso2": "CU",
    "phoneCode": "53",
    "currency": "CUP",
    "currencySymbol": "$",
    "native": "Cuba",
    "region": "Americas",
    "latitude": 21.5,
    "longitude": -80
  },
  {
    "id": 57,
    "name": "Cyprus",
    "iso3": "CYP",
    "iso2": "CY",
    "phoneCode": "357",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Κύπρος",
    "region": "Europe",
    "latitude": 35,
    "longitude": 33
  },
  {
    "id": 58,
    "name": "Czech Republic",
    "iso3": "CZE",
    "iso2": "CZ",
    "phoneCode": "420",
    "currency": "CZK",
    "currencySymbol": "Kč",
    "native": "Česká republika",
    "region": "Europe",
    "latitude": 49.75,
    "longitude": 15.5
  },
  {
    "id": 59,
    "name": "Denmark",
    "iso3": "DNK",
    "iso2": "DK",
    "phoneCode": "45",
    "currency": "DKK",
    "currencySymbol": "Kr.",
    "native": "Danmark",
    "region": "Europe",
    "latitude": 56,
    "longitude": 10
  },
  {
    "id": 60,
    "name": "Djibouti",
    "iso3": "DJI",
    "iso2": "DJ",
    "phoneCode": "253",
    "currency": "DJF",
    "currencySymbol": "Fdj",
    "native": "Djibouti",
    "region": "Africa",
    "latitude": 11.5,
    "longitude": 43
  },
  {
    "id": 61,
    "name": "Dominica",
    "iso3": "DMA",
    "iso2": "DM",
    "phoneCode": "+1-767",
    "currency": "XCD",
    "currencySymbol": "$",
    "native": "Dominica",
    "region": "Americas",
    "latitude": 15.41666666,
    "longitude": -61.33333333
  },
  {
    "id": 62,
    "name": "Dominican Republic",
    "iso3": "DOM",
    "iso2": "DO",
    "phoneCode": "+1-809 and 1-829",
    "currency": "DOP",
    "currencySymbol": "$",
    "native": "República Dominicana",
    "region": "Americas",
    "latitude": 19,
    "longitude": -70.66666666
  },
  {
    "id": 63,
    "name": "East Timor",
    "iso3": "TLS",
    "iso2": "TL",
    "phoneCode": "670",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "Timor-Leste",
    "region": "Asia",
    "latitude": -8.83333333,
    "longitude": 125.91666666
  },
  {
    "id": 64,
    "name": "Ecuador",
    "iso3": "ECU",
    "iso2": "EC",
    "phoneCode": "593",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "Ecuador",
    "region": "Americas",
    "latitude": -2,
    "longitude": -77.5
  },
  {
    "id": 65,
    "name": "Egypt",
    "iso3": "EGY",
    "iso2": "EG",
    "phoneCode": "20",
    "currency": "EGP",
    "currencySymbol": "ج.م",
    "native": "مصر‎",
    "region": "Africa",
    "latitude": 27,
    "longitude": 30
  },
  {
    "id": 66,
    "name": "El Salvador",
    "iso3": "SLV",
    "iso2": "SV",
    "phoneCode": "503",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "El Salvador",
    "region": "Americas",
    "latitude": 13.83333333,
    "longitude": -88.91666666
  },
  {
    "id": 67,
    "name": "Equatorial Guinea",
    "iso3": "GNQ",
    "iso2": "GQ",
    "phoneCode": "240",
    "currency": "XAF",
    "currencySymbol": "FCFA",
    "native": "Guinea Ecuatorial",
    "region": "Africa",
    "latitude": 2,
    "longitude": 10
  },
  {
    "id": 68,
    "name": "Eritrea",
    "iso3": "ERI",
    "iso2": "ER",
    "phoneCode": "291",
    "currency": "ERN",
    "currencySymbol": "Nfk",
    "native": "ኤርትራ",
    "region": "Africa",
    "latitude": 15,
    "longitude": 39
  },
  {
    "id": 69,
    "name": "Estonia",
    "iso3": "EST",
    "iso2": "EE",
    "phoneCode": "372",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Eesti",
    "region": "Europe",
    "latitude": 59,
    "longitude": 26
  },
  {
    "id": 70,
    "name": "Ethiopia",
    "iso3": "ETH",
    "iso2": "ET",
    "phoneCode": "251",
    "currency": "ETB",
    "currencySymbol": "Nkf",
    "native": "ኢትዮጵያ",
    "region": "Africa",
    "latitude": 8,
    "longitude": 38
  },
  {
    "id": 71,
    "name": "Falkland Islands",
    "iso3": "FLK",
    "iso2": "FK",
    "phoneCode": "500",
    "currency": "FKP",
    "currencySymbol": "£",
    "native": "Falkland Islands",
    "region": "Americas",
    "latitude": -51.75,
    "longitude": -59
  },
  {
    "id": 72,
    "name": "Faroe Islands",
    "iso3": "FRO",
    "iso2": "FO",
    "phoneCode": "298",
    "currency": "DKK",
    "currencySymbol": "Kr.",
    "native": "Føroyar",
    "region": "Europe",
    "latitude": 62,
    "longitude": -7
  },
  {
    "id": 73,
    "name": "Fiji Islands",
    "iso3": "FJI",
    "iso2": "FJ",
    "phoneCode": "679",
    "currency": "FJD",
    "currencySymbol": "FJ$",
    "native": "Fiji",
    "region": "Oceania",
    "latitude": -18,
    "longitude": 175
  },
  {
    "id": 74,
    "name": "Finland",
    "iso3": "FIN",
    "iso2": "FI",
    "phoneCode": "358",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Suomi",
    "region": "Europe",
    "latitude": 64,
    "longitude": 26
  },
  {
    "id": 75,
    "name": "France",
    "iso3": "FRA",
    "iso2": "FR",
    "phoneCode": "33",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "France",
    "region": "Europe",
    "latitude": 46,
    "longitude": 2
  },
  {
    "id": 76,
    "name": "French Guiana",
    "iso3": "GUF",
    "iso2": "GF",
    "phoneCode": "594",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Guyane française",
    "region": "Americas",
    "latitude": 4,
    "longitude": -53
  },
  {
    "id": 77,
    "name": "French Polynesia",
    "iso3": "PYF",
    "iso2": "PF",
    "phoneCode": "689",
    "currency": "XPF",
    "currencySymbol": "₣",
    "native": "Polynésie française",
    "region": "Oceania",
    "latitude": -15,
    "longitude": -140
  },
  {
    "id": 78,
    "name": "French Southern Territories",
    "iso3": "ATF",
    "iso2": "TF",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Territoire des Terres australes et antarctiques fr",
    "region": "Africa",
    "latitude": -49.25,
    "longitude": 69.167
  },
  {
    "id": 79,
    "name": "Gabon",
    "iso3": "GAB",
    "iso2": "GA",
    "phoneCode": "241",
    "currency": "XAF",
    "currencySymbol": "FCFA",
    "native": "Gabon",
    "region": "Africa",
    "latitude": -1,
    "longitude": 11.75
  },
  {
    "id": 80,
    "name": "Gambia The",
    "iso3": "GMB",
    "iso2": "GM",
    "phoneCode": "220",
    "currency": "GMD",
    "currencySymbol": "D",
    "native": "Gambia",
    "region": "Africa",
    "latitude": 13.46666666,
    "longitude": -16.56666666
  },
  {
    "id": 81,
    "name": "Georgia",
    "iso3": "GEO",
    "iso2": "GE",
    "phoneCode": "995",
    "currency": "GEL",
    "currencySymbol": "ლ",
    "native": "საქართველო",
    "region": "Asia",
    "latitude": 42,
    "longitude": 43.5
  },
  {
    "id": 82,
    "name": "Germany",
    "iso3": "DEU",
    "iso2": "DE",
    "phoneCode": "49",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Deutschland",
    "region": "Europe",
    "latitude": 51,
    "longitude": 9
  },
  {
    "id": 83,
    "name": "Ghana",
    "iso3": "GHA",
    "iso2": "GH",
    "phoneCode": "233",
    "currency": "GHS",
    "currencySymbol": "GH₵",
    "native": "Ghana",
    "region": "Africa",
    "latitude": 8,
    "longitude": -2
  },
  {
    "id": 84,
    "name": "Gibraltar",
    "iso3": "GIB",
    "iso2": "GI",
    "phoneCode": "350",
    "currency": "GIP",
    "currencySymbol": "£",
    "native": "Gibraltar",
    "region": "Europe",
    "latitude": 36.13333333,
    "longitude": -5.35
  },
  {
    "id": 85,
    "name": "Greece",
    "iso3": "GRC",
    "iso2": "GR",
    "phoneCode": "30",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Ελλάδα",
    "region": "Europe",
    "latitude": 39,
    "longitude": 22
  },
  {
    "id": 86,
    "name": "Greenland",
    "iso3": "GRL",
    "iso2": "GL",
    "phoneCode": "299",
    "currency": "DKK",
    "currencySymbol": "Kr.",
    "native": "Kalaallit Nunaat",
    "region": "Americas",
    "latitude": 72,
    "longitude": -40
  },
  {
    "id": 87,
    "name": "Grenada",
    "iso3": "GRD",
    "iso2": "GD",
    "phoneCode": "+1-473",
    "currency": "XCD",
    "currencySymbol": "$",
    "native": "Grenada",
    "region": "Americas",
    "latitude": 12.11666666,
    "longitude": -61.66666666
  },
  {
    "id": 88,
    "name": "Guadeloupe",
    "iso3": "GLP",
    "iso2": "GP",
    "phoneCode": "590",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Guadeloupe",
    "region": "Americas",
    "latitude": 16.25,
    "longitude": -61.583333
  },
  {
    "id": 89,
    "name": "Guam",
    "iso3": "GUM",
    "iso2": "GU",
    "phoneCode": "+1-671",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "Guam",
    "region": "Oceania",
    "latitude": 13.46666666,
    "longitude": 144.78333333
  },
  {
    "id": 90,
    "name": "Guatemala",
    "iso3": "GTM",
    "iso2": "GT",
    "phoneCode": "502",
    "currency": "GTQ",
    "currencySymbol": "Q",
    "native": "Guatemala",
    "region": "Americas",
    "latitude": 15.5,
    "longitude": -90.25
  },
  {
    "id": 91,
    "name": "Guernsey and Alderney",
    "iso3": "GGY",
    "iso2": "GG",
    "phoneCode": "+44-1481",
    "currency": "GBP",
    "currencySymbol": "£",
    "native": "Guernsey",
    "region": "Europe",
    "latitude": 49.46666666,
    "longitude": -2.58333333
  },
  {
    "id": 92,
    "name": "Guinea",
    "iso3": "GIN",
    "iso2": "GN",
    "phoneCode": "224",
    "currency": "GNF",
    "currencySymbol": "FG",
    "native": "Guinée",
    "region": "Africa",
    "latitude": 11,
    "longitude": -10
  },
  {
    "id": 93,
    "name": "Guinea-Bissau",
    "iso3": "GNB",
    "iso2": "GW",
    "phoneCode": "245",
    "currency": "XOF",
    "currencySymbol": "CFA",
    "native": "Guiné-Bissau",
    "region": "Africa",
    "latitude": 12,
    "longitude": -15
  },
  {
    "id": 94,
    "name": "Guyana",
    "iso3": "GUY",
    "iso2": "GY",
    "phoneCode": "592",
    "currency": "GYD",
    "currencySymbol": "$",
    "native": "Guyana",
    "region": "Americas",
    "latitude": 5,
    "longitude": -59
  },
  {
    "id": 95,
    "name": "Haiti",
    "iso3": "HTI",
    "iso2": "HT",
    "phoneCode": "509",
    "currency": "HTG",
    "currencySymbol": "G",
    "native": "Haïti",
    "region": "Americas",
    "latitude": 19,
    "longitude": -72.41666666
  },
  {
    "id": 96,
    "name": "Heard Island and McDonald Islands",
    "iso3": "HMD",
    "iso2": "HM",
    "currency": "AUD",
    "currencySymbol": "$",
    "native": "Heard Island and McDonald Islands",
    "region": "",
    "latitude": -53.1,
    "longitude": 72.51666666
  },
  {
    "id": 97,
    "name": "Honduras",
    "iso3": "HND",
    "iso2": "HN",
    "phoneCode": "504",
    "currency": "HNL",
    "currencySymbol": "L",
    "native": "Honduras",
    "region": "Americas",
    "latitude": 15,
    "longitude": -86.5
  },
  {
    "id": 98,
    "name": "Hong Kong S.A.R.",
    "iso3": "HKG",
    "iso2": "HK",
    "phoneCode": "852",
    "currency": "HKD",
    "currencySymbol": "$",
    "native": "香港",
    "region": "Asia",
    "latitude": 22.25,
    "longitude": 114.16666666
  },
  {
    "id": 99,
    "name": "Hungary",
    "iso3": "HUN",
    "iso2": "HU",
    "phoneCode": "36",
    "currency": "HUF",
    "currencySymbol": "Ft",
    "native": "Magyarország",
    "region": "Europe",
    "latitude": 47,
    "longitude": 20
  },
  {
    "id": 100,
    "name": "Iceland",
    "iso3": "ISL",
    "iso2": "IS",
    "phoneCode": "354",
    "currency": "ISK",
    "currencySymbol": "kr",
    "native": "Ísland",
    "region": "Europe",
    "latitude": 65,
    "longitude": -18
  },
  {
    "id": 101,
    "name": "India",
    "iso3": "IND",
    "iso2": "IN",
    "phoneCode": "91",
    "currency": "INR",
    "currencySymbol": "₹",
    "native": "भारत",
    "region": "Asia",
    "latitude": 20,
    "longitude": 77
  },
  {
    "id": 102,
    "name": "Indonesia",
    "iso3": "IDN",
    "iso2": "ID",
    "phoneCode": "62",
    "currency": "IDR",
    "currencySymbol": "Rp",
    "native": "Indonesia",
    "region": "Asia",
    "latitude": -5,
    "longitude": 120
  },
  {
    "id": 103,
    "name": "Iran",
    "iso3": "IRN",
    "iso2": "IR",
    "phoneCode": "98",
    "currency": "IRR",
    "currencySymbol": "﷼",
    "native": "ایران",
    "region": "Asia",
    "latitude": 32,
    "longitude": 53
  },
  {
    "id": 104,
    "name": "Iraq",
    "iso3": "IRQ",
    "iso2": "IQ",
    "phoneCode": "964",
    "currency": "IQD",
    "currencySymbol": "د.ع",
    "native": "العراق",
    "region": "Asia",
    "latitude": 33,
    "longitude": 44
  },
  {
    "id": 105,
    "name": "Ireland",
    "iso3": "IRL",
    "iso2": "IE",
    "phoneCode": "353",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Éire",
    "region": "Europe",
    "latitude": 53,
    "longitude": -8
  },
  {
    "id": 106,
    "name": "Israel",
    "iso3": "ISR",
    "iso2": "IL",
    "phoneCode": "972",
    "currency": "ILS",
    "currencySymbol": "₪",
    "native": "יִשְׂרָאֵל",
    "region": "Asia",
    "latitude": 31.5,
    "longitude": 34.75
  },
  {
    "id": 107,
    "name": "Italy",
    "iso3": "ITA",
    "iso2": "IT",
    "phoneCode": "39",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Italia",
    "region": "Europe",
    "latitude": 42.83333333,
    "longitude": 12.83333333
  },
  {
    "id": 108,
    "name": "Jamaica",
    "iso3": "JAM",
    "iso2": "JM",
    "phoneCode": "+1-876",
    "currency": "JMD",
    "currencySymbol": "J$",
    "native": "Jamaica",
    "region": "Americas",
    "latitude": 18.25,
    "longitude": -77.5
  },
  {
    "id": 109,
    "name": "Japan",
    "iso3": "JPN",
    "iso2": "JP",
    "phoneCode": "81",
    "currency": "JPY",
    "currencySymbol": "¥",
    "native": "日本",
    "region": "Asia",
    "latitude": 36,
    "longitude": 138
  },
  {
    "id": 110,
    "name": "Jersey",
    "iso3": "JEY",
    "iso2": "JE",
    "phoneCode": "+44-1534",
    "currency": "GBP",
    "currencySymbol": "£",
    "native": "Jersey",
    "region": "Europe",
    "latitude": 49.25,
    "longitude": -2.16666666
  },
  {
    "id": 111,
    "name": "Jordan",
    "iso3": "JOR",
    "iso2": "JO",
    "phoneCode": "962",
    "currency": "JOD",
    "currencySymbol": "ا.د",
    "native": "الأردن",
    "region": "Asia",
    "latitude": 31,
    "longitude": 36
  },
  {
    "id": 112,
    "name": "Kazakhstan",
    "iso3": "KAZ",
    "iso2": "KZ",
    "phoneCode": "7",
    "currency": "KZT",
    "currencySymbol": "лв",
    "native": "Қазақстан",
    "region": "Asia",
    "latitude": 48,
    "longitude": 68
  },
  {
    "id": 113,
    "name": "Kenya",
    "iso3": "KEN",
    "iso2": "KE",
    "phoneCode": "254",
    "currency": "KES",
    "currencySymbol": "KSh",
    "native": "Kenya",
    "region": "Africa",
    "latitude": 1,
    "longitude": 38
  },
  {
    "id": 114,
    "name": "Kiribati",
    "iso3": "KIR",
    "iso2": "KI",
    "phoneCode": "686",
    "currency": "AUD",
    "currencySymbol": "$",
    "native": "Kiribati",
    "region": "Oceania",
    "latitude": 1.41666666,
    "longitude": 173
  },
  {
    "id": 115,
    "name": "Korea North",
    "iso3": "PRK",
    "iso2": "KP",
    "phoneCode": "850",
    "currency": "KPW",
    "currencySymbol": "₩",
    "native": "북한",
    "region": "Asia",
    "latitude": 40,
    "longitude": 127
  },
  {
    "id": 116,
    "name": "Korea South",
    "iso3": "KOR",
    "iso2": "KR",
    "phoneCode": "82",
    "currency": "KRW",
    "currencySymbol": "₩",
    "native": "대한민국",
    "region": "Asia",
    "latitude": 37,
    "longitude": 127.5
  },
  {
    "id": 117,
    "name": "Kuwait",
    "iso3": "KWT",
    "iso2": "KW",
    "phoneCode": "965",
    "currency": "KWD",
    "currencySymbol": "ك.د",
    "native": "الكويت",
    "region": "Asia",
    "latitude": 29.5,
    "longitude": 45.75
  },
  {
    "id": 118,
    "name": "Kyrgyzstan",
    "iso3": "KGZ",
    "iso2": "KG",
    "phoneCode": "996",
    "currency": "KGS",
    "currencySymbol": "лв",
    "native": "Кыргызстан",
    "region": "Asia",
    "latitude": 41,
    "longitude": 75
  },
  {
    "id": 119,
    "name": "Laos",
    "iso3": "LAO",
    "iso2": "LA",
    "phoneCode": "856",
    "currency": "LAK",
    "currencySymbol": "₭",
    "native": "ສປປລາວ",
    "region": "Asia",
    "latitude": 18,
    "longitude": 105
  },
  {
    "id": 120,
    "name": "Latvia",
    "iso3": "LVA",
    "iso2": "LV",
    "phoneCode": "371",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Latvija",
    "region": "Europe",
    "latitude": 57,
    "longitude": 25
  },
  {
    "id": 121,
    "name": "Lebanon",
    "iso3": "LBN",
    "iso2": "LB",
    "phoneCode": "961",
    "currency": "LBP",
    "currencySymbol": "£",
    "native": "لبنان",
    "region": "Asia",
    "latitude": 33.83333333,
    "longitude": 35.83333333
  },
  {
    "id": 122,
    "name": "Lesotho",
    "iso3": "LSO",
    "iso2": "LS",
    "phoneCode": "266",
    "currency": "LSL",
    "currencySymbol": "L",
    "native": "Lesotho",
    "region": "Africa",
    "latitude": -29.5,
    "longitude": 28.5
  },
  {
    "id": 123,
    "name": "Liberia",
    "iso3": "LBR",
    "iso2": "LR",
    "phoneCode": "231",
    "currency": "LRD",
    "currencySymbol": "$",
    "native": "Liberia",
    "region": "Africa",
    "latitude": 6.5,
    "longitude": -9.5
  },
  {
    "id": 124,
    "name": "Libya",
    "iso3": "LBY",
    "iso2": "LY",
    "phoneCode": "218",
    "currency": "LYD",
    "currencySymbol": "د.ل",
    "native": "‏ليبيا",
    "region": "Africa",
    "latitude": 25,
    "longitude": 17
  },
  {
    "id": 125,
    "name": "Liechtenstein",
    "iso3": "LIE",
    "iso2": "LI",
    "phoneCode": "423",
    "currency": "CHF",
    "currencySymbol": "CHf",
    "native": "Liechtenstein",
    "region": "Europe",
    "latitude": 47.26666666,
    "longitude": 9.53333333
  },
  {
    "id": 126,
    "name": "Lithuania",
    "iso3": "LTU",
    "iso2": "LT",
    "phoneCode": "370",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Lietuva",
    "region": "Europe",
    "latitude": 56,
    "longitude": 24
  },
  {
    "id": 127,
    "name": "Luxembourg",
    "iso3": "LUX",
    "iso2": "LU",
    "phoneCode": "352",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Luxembourg",
    "region": "Europe",
    "latitude": 49.75,
    "longitude": 6.16666666
  },
  {
    "id": 128,
    "name": "Macau S.A.R.",
    "iso3": "MAC",
    "iso2": "MO",
    "phoneCode": "853",
    "currency": "MOP",
    "currencySymbol": "$",
    "native": "澳門",
    "region": "Asia",
    "latitude": 22.16666666,
    "longitude": 113.55
  },
  {
    "id": 129,
    "name": "Macedonia",
    "iso3": "MKD",
    "iso2": "MK",
    "phoneCode": "389",
    "currency": "MKD",
    "currencySymbol": "ден",
    "native": "Северна Македонија",
    "region": "Europe",
    "latitude": 41.83333333,
    "longitude": 22
  },
  {
    "id": 130,
    "name": "Madagascar",
    "iso3": "MDG",
    "iso2": "MG",
    "phoneCode": "261",
    "currency": "MGA",
    "currencySymbol": "Ar",
    "native": "Madagasikara",
    "region": "Africa",
    "latitude": -20,
    "longitude": 47
  },
  {
    "id": 131,
    "name": "Malawi",
    "iso3": "MWI",
    "iso2": "MW",
    "phoneCode": "265",
    "currency": "MWK",
    "currencySymbol": "MK",
    "native": "Malawi",
    "region": "Africa",
    "latitude": -13.5,
    "longitude": 34
  },
  {
    "id": 132,
    "name": "Malaysia",
    "iso3": "MYS",
    "iso2": "MY",
    "phoneCode": "60",
    "currency": "MYR",
    "currencySymbol": "RM",
    "native": "Malaysia",
    "region": "Asia",
    "latitude": 2.5,
    "longitude": 112.5
  },
  {
    "id": 133,
    "name": "Maldives",
    "iso3": "MDV",
    "iso2": "MV",
    "phoneCode": "960",
    "currency": "MVR",
    "currencySymbol": "Rf",
    "native": "Maldives",
    "region": "Asia",
    "latitude": 3.25,
    "longitude": 73
  },
  {
    "id": 134,
    "name": "Mali",
    "iso3": "MLI",
    "iso2": "ML",
    "phoneCode": "223",
    "currency": "XOF",
    "currencySymbol": "CFA",
    "native": "Mali",
    "region": "Africa",
    "latitude": 17,
    "longitude": -4
  },
  {
    "id": 135,
    "name": "Malta",
    "iso3": "MLT",
    "iso2": "MT",
    "phoneCode": "356",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Malta",
    "region": "Europe",
    "latitude": 35.83333333,
    "longitude": 14.58333333
  },
  {
    "id": 136,
    "name": "Man (Isle of)",
    "iso3": "IMN",
    "iso2": "IM",
    "phoneCode": "+44-1624",
    "currency": "GBP",
    "currencySymbol": "£",
    "native": "Isle of Man",
    "region": "Europe",
    "latitude": 54.25,
    "longitude": -4.5
  },
  {
    "id": 137,
    "name": "Marshall Islands",
    "iso3": "MHL",
    "iso2": "MH",
    "phoneCode": "692",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "M̧ajeļ",
    "region": "Oceania",
    "latitude": 9,
    "longitude": 168
  },
  {
    "id": 138,
    "name": "Martinique",
    "iso3": "MTQ",
    "iso2": "MQ",
    "phoneCode": "596",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Martinique",
    "region": "Americas",
    "latitude": 14.666667,
    "longitude": -61
  },
  {
    "id": 139,
    "name": "Mauritania",
    "iso3": "MRT",
    "iso2": "MR",
    "phoneCode": "222",
    "currency": "MRO",
    "currencySymbol": "MRU",
    "native": "موريتانيا",
    "region": "Africa",
    "latitude": 20,
    "longitude": -12
  },
  {
    "id": 140,
    "name": "Mauritius",
    "iso3": "MUS",
    "iso2": "MU",
    "phoneCode": "230",
    "currency": "MUR",
    "currencySymbol": "₨",
    "native": "Maurice",
    "region": "Africa",
    "latitude": -20.28333333,
    "longitude": 57.55
  },
  {
    "id": 141,
    "name": "Mayotte",
    "iso3": "MYT",
    "iso2": "YT",
    "phoneCode": "262",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Mayotte",
    "region": "Africa",
    "latitude": -12.83333333,
    "longitude": 45.16666666
  },
  {
    "id": 142,
    "name": "Mexico",
    "iso3": "MEX",
    "iso2": "MX",
    "phoneCode": "52",
    "currency": "MXN",
    "currencySymbol": "$",
    "native": "México",
    "region": "Americas",
    "latitude": 23,
    "longitude": -102
  },
  {
    "id": 143,
    "name": "Micronesia",
    "iso3": "FSM",
    "iso2": "FM",
    "phoneCode": "691",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "Micronesia",
    "region": "Oceania",
    "latitude": 6.91666666,
    "longitude": 158.25
  },
  {
    "id": 144,
    "name": "Moldova",
    "iso3": "MDA",
    "iso2": "MD",
    "phoneCode": "373",
    "currency": "MDL",
    "currencySymbol": "L",
    "native": "Moldova",
    "region": "Europe",
    "latitude": 47,
    "longitude": 29
  },
  {
    "id": 145,
    "name": "Monaco",
    "iso3": "MCO",
    "iso2": "MC",
    "phoneCode": "377",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Monaco",
    "region": "Europe",
    "latitude": 43.73333333,
    "longitude": 7.4
  },
  {
    "id": 146,
    "name": "Mongolia",
    "iso3": "MNG",
    "iso2": "MN",
    "phoneCode": "976",
    "currency": "MNT",
    "currencySymbol": "₮",
    "native": "Монгол улс",
    "region": "Asia",
    "latitude": 46,
    "longitude": 105
  },
  {
    "id": 147,
    "name": "Montenegro",
    "iso3": "MNE",
    "iso2": "ME",
    "phoneCode": "382",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Црна Гора",
    "region": "Europe",
    "latitude": 42.5,
    "longitude": 19.3
  },
  {
    "id": 148,
    "name": "Montserrat",
    "iso3": "MSR",
    "iso2": "MS",
    "phoneCode": "+1-664",
    "currency": "XCD",
    "currencySymbol": "$",
    "native": "Montserrat",
    "region": "Americas",
    "latitude": 16.75,
    "longitude": -62.2
  },
  {
    "id": 149,
    "name": "Morocco",
    "iso3": "MAR",
    "iso2": "MA",
    "phoneCode": "212",
    "currency": "MAD",
    "currencySymbol": "DH",
    "native": "المغرب",
    "region": "Africa",
    "latitude": 32,
    "longitude": -5
  },
  {
    "id": 150,
    "name": "Mozambique",
    "iso3": "MOZ",
    "iso2": "MZ",
    "phoneCode": "258",
    "currency": "MZN",
    "currencySymbol": "MT",
    "native": "Moçambique",
    "region": "Africa",
    "latitude": -18.25,
    "longitude": 35
  },
  {
    "id": 151,
    "name": "Myanmar",
    "iso3": "MMR",
    "iso2": "MM",
    "phoneCode": "95",
    "currency": "MMK",
    "currencySymbol": "K",
    "native": "မြန်မာ",
    "region": "Asia",
    "latitude": 22,
    "longitude": 98
  },
  {
    "id": 152,
    "name": "Namibia",
    "iso3": "NAM",
    "iso2": "NA",
    "phoneCode": "264",
    "currency": "NAD",
    "currencySymbol": "$",
    "native": "Namibia",
    "region": "Africa",
    "latitude": -22,
    "longitude": 17
  },
  {
    "id": 153,
    "name": "Nauru",
    "iso3": "NRU",
    "iso2": "NR",
    "phoneCode": "674",
    "currency": "AUD",
    "currencySymbol": "$",
    "native": "Nauru",
    "region": "Oceania",
    "latitude": -0.53333333,
    "longitude": 166.91666666
  },
  {
    "id": 154,
    "name": "Nepal",
    "iso3": "NPL",
    "iso2": "NP",
    "phoneCode": "977",
    "currency": "NPR",
    "currencySymbol": "₨",
    "native": "नपल",
    "region": "Asia",
    "latitude": 28,
    "longitude": 84
  },
  {
    "id": 155,
    "name": "Bonaire, Sint Eustatius and Saba",
    "iso3": "BES",
    "iso2": "BQ",
    "phoneCode": "599",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "Caribisch Nederland",
    "region": "Americas",
    "latitude": 12.15,
    "longitude": -68.266667
  },
  {
    "id": 156,
    "name": "Netherlands The",
    "iso3": "NLD",
    "iso2": "NL",
    "phoneCode": "31",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Nederland",
    "region": "Europe",
    "latitude": 52.5,
    "longitude": 5.75
  },
  {
    "id": 157,
    "name": "New Caledonia",
    "iso3": "NCL",
    "iso2": "NC",
    "phoneCode": "687",
    "currency": "XPF",
    "currencySymbol": "₣",
    "native": "Nouvelle-Calédonie",
    "region": "Oceania",
    "latitude": -21.5,
    "longitude": 165.5
  },
  {
    "id": 158,
    "name": "New Zealand",
    "iso3": "NZL",
    "iso2": "NZ",
    "phoneCode": "64",
    "currency": "NZD",
    "currencySymbol": "$",
    "native": "New Zealand",
    "region": "Oceania",
    "latitude": -41,
    "longitude": 174
  },
  {
    "id": 159,
    "name": "Nicaragua",
    "iso3": "NIC",
    "iso2": "NI",
    "phoneCode": "505",
    "currency": "NIO",
    "currencySymbol": "C$",
    "native": "Nicaragua",
    "region": "Americas",
    "latitude": 13,
    "longitude": -85
  },
  {
    "id": 160,
    "name": "Niger",
    "iso3": "NER",
    "iso2": "NE",
    "phoneCode": "227",
    "currency": "XOF",
    "currencySymbol": "CFA",
    "native": "Niger",
    "region": "Africa",
    "latitude": 16,
    "longitude": 8
  },
  {
    "id": 161,
    "name": "Nigeria",
    "iso3": "NGA",
    "iso2": "NG",
    "phoneCode": "234",
    "currency": "NGN",
    "currencySymbol": "₦",
    "native": "Nigeria",
    "region": "Africa",
    "latitude": 10,
    "longitude": 8
  },
  {
    "id": 162,
    "name": "Niue",
    "iso3": "NIU",
    "iso2": "NU",
    "phoneCode": "683",
    "currency": "NZD",
    "currencySymbol": "$",
    "native": "Niuē",
    "region": "Oceania",
    "latitude": -19.03333333,
    "longitude": -169.86666666
  },
  {
    "id": 163,
    "name": "Norfolk Island",
    "iso3": "NFK",
    "iso2": "NF",
    "phoneCode": "672",
    "currency": "AUD",
    "currencySymbol": "$",
    "native": "Norfolk Island",
    "region": "Oceania",
    "latitude": -29.03333333,
    "longitude": 167.95
  },
  {
    "id": 164,
    "name": "Northern Mariana Islands",
    "iso3": "MNP",
    "iso2": "MP",
    "phoneCode": "+1-670",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "Northern Mariana Islands",
    "region": "Oceania",
    "latitude": 15.2,
    "longitude": 145.75
  },
  {
    "id": 165,
    "name": "Norway",
    "iso3": "NOR",
    "iso2": "NO",
    "phoneCode": "47",
    "currency": "NOK",
    "currencySymbol": "kr",
    "native": "Norge",
    "region": "Europe",
    "latitude": 62,
    "longitude": 10
  },
  {
    "id": 166,
    "name": "Oman",
    "iso3": "OMN",
    "iso2": "OM",
    "phoneCode": "968",
    "currency": "OMR",
    "currencySymbol": ".ع.ر",
    "native": "عمان",
    "region": "Asia",
    "latitude": 21,
    "longitude": 57
  },
  {
    "id": 167,
    "name": "Pakistan",
    "iso3": "PAK",
    "iso2": "PK",
    "phoneCode": "92",
    "currency": "PKR",
    "currencySymbol": "₨",
    "native": "Pakistan",
    "region": "Asia",
    "latitude": 30,
    "longitude": 70
  },
  {
    "id": 168,
    "name": "Palau",
    "iso3": "PLW",
    "iso2": "PW",
    "phoneCode": "680",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "Palau",
    "region": "Oceania",
    "latitude": 7.5,
    "longitude": 134.5
  },
  {
    "id": 169,
    "name": "Palestinian Territory Occupied",
    "iso3": "PSE",
    "iso2": "PS",
    "phoneCode": "970",
    "currency": "ILS",
    "currencySymbol": "₪",
    "native": "فلسطين",
    "region": "Asia",
    "latitude": 31.9,
    "longitude": 35.2
  },
  {
    "id": 170,
    "name": "Panama",
    "iso3": "PAN",
    "iso2": "PA",
    "phoneCode": "507",
    "currency": "PAB",
    "currencySymbol": "B/.",
    "native": "Panamá",
    "region": "Americas",
    "latitude": 9,
    "longitude": -80
  },
  {
    "id": 171,
    "name": "Papua new Guinea",
    "iso3": "PNG",
    "iso2": "PG",
    "phoneCode": "675",
    "currency": "PGK",
    "currencySymbol": "K",
    "native": "Papua Niugini",
    "region": "Oceania",
    "latitude": -6,
    "longitude": 147
  },
  {
    "id": 172,
    "name": "Paraguay",
    "iso3": "PRY",
    "iso2": "PY",
    "phoneCode": "595",
    "currency": "PYG",
    "currencySymbol": "₲",
    "native": "Paraguay",
    "region": "Americas",
    "latitude": -23,
    "longitude": -58
  },
  {
    "id": 173,
    "name": "Peru",
    "iso3": "PER",
    "iso2": "PE",
    "phoneCode": "51",
    "currency": "PEN",
    "currencySymbol": "S/.",
    "native": "Perú",
    "region": "Americas",
    "latitude": -10,
    "longitude": -76
  },
  {
    "id": 174,
    "name": "Philippines",
    "iso3": "PHL",
    "iso2": "PH",
    "phoneCode": "63",
    "currency": "PHP",
    "currencySymbol": "₱",
    "native": "Pilipinas",
    "region": "Asia",
    "latitude": 13,
    "longitude": 122
  },
  {
    "id": 175,
    "name": "Pitcairn Island",
    "iso3": "PCN",
    "iso2": "PN",
    "phoneCode": "870",
    "currency": "NZD",
    "currencySymbol": "$",
    "native": "Pitcairn Islands",
    "region": "Oceania",
    "latitude": -25.06666666,
    "longitude": -130.1
  },
  {
    "id": 176,
    "name": "Poland",
    "iso3": "POL",
    "iso2": "PL",
    "phoneCode": "48",
    "currency": "PLN",
    "currencySymbol": "zł",
    "native": "Polska",
    "region": "Europe",
    "latitude": 52,
    "longitude": 20
  },
  {
    "id": 177,
    "name": "Portugal",
    "iso3": "PRT",
    "iso2": "PT",
    "phoneCode": "351",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Portugal",
    "region": "Europe",
    "latitude": 39.5,
    "longitude": -8
  },
  {
    "id": 178,
    "name": "Puerto Rico",
    "iso3": "PRI",
    "iso2": "PR",
    "phoneCode": "+1-787 and 1-939",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "Puerto Rico",
    "region": "Americas",
    "latitude": 18.25,
    "longitude": -66.5
  },
  {
    "id": 179,
    "name": "Qatar",
    "iso3": "QAT",
    "iso2": "QA",
    "phoneCode": "974",
    "currency": "QAR",
    "currencySymbol": "ق.ر",
    "native": "قطر",
    "region": "Asia",
    "latitude": 25.5,
    "longitude": 51.25
  },
  {
    "id": 180,
    "name": "Reunion",
    "iso3": "REU",
    "iso2": "RE",
    "phoneCode": "262",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "La Réunion",
    "region": "Africa",
    "latitude": -21.15,
    "longitude": 55.5
  },
  {
    "id": 181,
    "name": "Romania",
    "iso3": "ROU",
    "iso2": "RO",
    "phoneCode": "40",
    "currency": "RON",
    "currencySymbol": "lei",
    "native": "România",
    "region": "Europe",
    "latitude": 46,
    "longitude": 25
  },
  {
    "id": 182,
    "name": "Russia",
    "iso3": "RUS",
    "iso2": "RU",
    "phoneCode": "7",
    "currency": "RUB",
    "currencySymbol": "₽",
    "native": "Россия",
    "region": "Europe",
    "latitude": 60,
    "longitude": 100
  },
  {
    "id": 183,
    "name": "Rwanda",
    "iso3": "RWA",
    "iso2": "RW",
    "phoneCode": "250",
    "currency": "RWF",
    "currencySymbol": "FRw",
    "native": "Rwanda",
    "region": "Africa",
    "latitude": -2,
    "longitude": 30
  },
  {
    "id": 184,
    "name": "Saint Helena",
    "iso3": "SHN",
    "iso2": "SH",
    "phoneCode": "290",
    "currency": "SHP",
    "currencySymbol": "£",
    "native": "Saint Helena",
    "region": "Africa",
    "latitude": -15.95,
    "longitude": -5.7
  },
  {
    "id": 185,
    "name": "Saint Kitts And Nevis",
    "iso3": "KNA",
    "iso2": "KN",
    "phoneCode": "+1-869",
    "currency": "XCD",
    "currencySymbol": "$",
    "native": "Saint Kitts and Nevis",
    "region": "Americas",
    "latitude": 17.33333333,
    "longitude": -62.75
  },
  {
    "id": 186,
    "name": "Saint Lucia",
    "iso3": "LCA",
    "iso2": "LC",
    "phoneCode": "+1-758",
    "currency": "XCD",
    "currencySymbol": "$",
    "native": "Saint Lucia",
    "region": "Americas",
    "latitude": 13.88333333,
    "longitude": -60.96666666
  },
  {
    "id": 187,
    "name": "Saint Pierre and Miquelon",
    "iso3": "SPM",
    "iso2": "PM",
    "phoneCode": "508",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Saint-Pierre-et-Miquelon",
    "region": "Americas",
    "latitude": 46.83333333,
    "longitude": -56.33333333
  },
  {
    "id": 188,
    "name": "Saint Vincent And The Grenadines",
    "iso3": "VCT",
    "iso2": "VC",
    "phoneCode": "+1-784",
    "currency": "XCD",
    "currencySymbol": "$",
    "native": "Saint Vincent and the Grenadines",
    "region": "Americas",
    "latitude": 13.25,
    "longitude": -61.2
  },
  {
    "id": 189,
    "name": "Saint-Barthelemy",
    "iso3": "BLM",
    "iso2": "BL",
    "phoneCode": "590",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Saint-Barthélemy",
    "region": "Americas",
    "latitude": 18.5,
    "longitude": -63.41666666
  },
  {
    "id": 190,
    "name": "Saint-Martin (French part)",
    "iso3": "MAF",
    "iso2": "MF",
    "phoneCode": "590",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Saint-Martin",
    "region": "Americas",
    "latitude": 18.08333333,
    "longitude": -63.95
  },
  {
    "id": 191,
    "name": "Samoa",
    "iso3": "WSM",
    "iso2": "WS",
    "phoneCode": "685",
    "currency": "WST",
    "currencySymbol": "SAT",
    "native": "Samoa",
    "region": "Oceania",
    "latitude": -13.58333333,
    "longitude": -172.33333333
  },
  {
    "id": 192,
    "name": "San Marino",
    "iso3": "SMR",
    "iso2": "SM",
    "phoneCode": "378",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "San Marino",
    "region": "Europe",
    "latitude": 43.76666666,
    "longitude": 12.41666666
  },
  {
    "id": 193,
    "name": "Sao Tome and Principe",
    "iso3": "STP",
    "iso2": "ST",
    "phoneCode": "239",
    "currency": "STD",
    "currencySymbol": "Db",
    "native": "São Tomé e Príncipe",
    "region": "Africa",
    "latitude": 1,
    "longitude": 7
  },
  {
    "id": 194,
    "name": "Saudi Arabia",
    "iso3": "SAU",
    "iso2": "SA",
    "phoneCode": "966",
    "currency": "SAR",
    "currencySymbol": "﷼",
    "native": "العربية السعودية",
    "region": "Asia",
    "latitude": 25,
    "longitude": 45
  },
  {
    "id": 195,
    "name": "Senegal",
    "iso3": "SEN",
    "iso2": "SN",
    "phoneCode": "221",
    "currency": "XOF",
    "currencySymbol": "CFA",
    "native": "Sénégal",
    "region": "Africa",
    "latitude": 14,
    "longitude": -14
  },
  {
    "id": 196,
    "name": "Serbia",
    "iso3": "SRB",
    "iso2": "RS",
    "phoneCode": "381",
    "currency": "RSD",
    "currencySymbol": "din",
    "native": "Србија",
    "region": "Europe",
    "latitude": 44,
    "longitude": 21
  },
  {
    "id": 197,
    "name": "Seychelles",
    "iso3": "SYC",
    "iso2": "SC",
    "phoneCode": "248",
    "currency": "SCR",
    "currencySymbol": "SRe",
    "native": "Seychelles",
    "region": "Africa",
    "latitude": -4.58333333,
    "longitude": 55.66666666
  },
  {
    "id": 198,
    "name": "Sierra Leone",
    "iso3": "SLE",
    "iso2": "SL",
    "phoneCode": "232",
    "currency": "SLL",
    "currencySymbol": "Le",
    "native": "Sierra Leone",
    "region": "Africa",
    "latitude": 8.5,
    "longitude": -11.5
  },
  {
    "id": 199,
    "name": "Singapore",
    "iso3": "SGP",
    "iso2": "SG",
    "phoneCode": "65",
    "currency": "SGD",
    "currencySymbol": "$",
    "native": "Singapore",
    "region": "Asia",
    "latitude": 1.36666666,
    "longitude": 103.8
  },
  {
    "id": 200,
    "name": "Slovakia",
    "iso3": "SVK",
    "iso2": "SK",
    "phoneCode": "421",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Slovensko",
    "region": "Europe",
    "latitude": 48.66666666,
    "longitude": 19.5
  },
  {
    "id": 201,
    "name": "Slovenia",
    "iso3": "SVN",
    "iso2": "SI",
    "phoneCode": "386",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Slovenija",
    "region": "Europe",
    "latitude": 46.11666666,
    "longitude": 14.81666666
  },
  {
    "id": 202,
    "name": "Solomon Islands",
    "iso3": "SLB",
    "iso2": "SB",
    "phoneCode": "677",
    "currency": "SBD",
    "currencySymbol": "Si$",
    "native": "Solomon Islands",
    "region": "Oceania",
    "latitude": -8,
    "longitude": 159
  },
  {
    "id": 203,
    "name": "Somalia",
    "iso3": "SOM",
    "iso2": "SO",
    "phoneCode": "252",
    "currency": "SOS",
    "currencySymbol": "Sh.so.",
    "native": "Soomaaliya",
    "region": "Africa",
    "latitude": 10,
    "longitude": 49
  },
  {
    "id": 204,
    "name": "South Africa",
    "iso3": "ZAF",
    "iso2": "ZA",
    "phoneCode": "27",
    "currency": "ZAR",
    "currencySymbol": "R",
    "native": "South Africa",
    "region": "Africa",
    "latitude": -29,
    "longitude": 24
  },
  {
    "id": 205,
    "name": "South Georgia",
    "iso3": "SGS",
    "iso2": "GS",
    "currency": "GBP",
    "currencySymbol": "£",
    "native": "South Georgia",
    "region": "Americas",
    "latitude": -54.5,
    "longitude": -37
  },
  {
    "id": 206,
    "name": "South Sudan",
    "iso3": "SSD",
    "iso2": "SS",
    "phoneCode": "211",
    "currency": "SSP",
    "currencySymbol": "£",
    "native": "South Sudan",
    "region": "Africa",
    "latitude": 7,
    "longitude": 30
  },
  {
    "id": 207,
    "name": "Spain",
    "iso3": "ESP",
    "iso2": "ES",
    "phoneCode": "34",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "España",
    "region": "Europe",
    "latitude": 40,
    "longitude": -4
  },
  {
    "id": 208,
    "name": "Sri Lanka",
    "iso3": "LKA",
    "iso2": "LK",
    "phoneCode": "94",
    "currency": "LKR",
    "currencySymbol": "Rs",
    "native": "śrī laṃkāva",
    "region": "Asia",
    "latitude": 7,
    "longitude": 81
  },
  {
    "id": 209,
    "name": "Sudan",
    "iso3": "SDN",
    "iso2": "SD",
    "phoneCode": "249",
    "currency": "SDG",
    "currencySymbol": ".س.ج",
    "native": "السودان",
    "region": "Africa",
    "latitude": 15,
    "longitude": 30
  },
  {
    "id": 210,
    "name": "Suriname",
    "iso3": "SUR",
    "iso2": "SR",
    "phoneCode": "597",
    "currency": "SRD",
    "currencySymbol": "$",
    "native": "Suriname",
    "region": "Americas",
    "latitude": 4,
    "longitude": -56
  },
  {
    "id": 211,
    "name": "Svalbard And Jan Mayen Islands",
    "iso3": "SJM",
    "iso2": "SJ",
    "phoneCode": "47",
    "currency": "NOK",
    "currencySymbol": "kr",
    "native": "Svalbard og Jan Mayen",
    "region": "Europe",
    "latitude": 78,
    "longitude": 20
  },
  {
    "id": 212,
    "name": "Swaziland",
    "iso3": "SWZ",
    "iso2": "SZ",
    "phoneCode": "268",
    "currency": "SZL",
    "currencySymbol": "E",
    "native": "Swaziland",
    "region": "Africa",
    "latitude": -26.5,
    "longitude": 31.5
  },
  {
    "id": 213,
    "name": "Sweden",
    "iso3": "SWE",
    "iso2": "SE",
    "phoneCode": "46",
    "currency": "SEK",
    "currencySymbol": "kr",
    "native": "Sverige",
    "region": "Europe",
    "latitude": 62,
    "longitude": 15
  },
  {
    "id": 214,
    "name": "Switzerland",
    "iso3": "CHE",
    "iso2": "CH",
    "phoneCode": "41",
    "currency": "CHF",
    "currencySymbol": "CHf",
    "native": "Schweiz",
    "region": "Europe",
    "latitude": 47,
    "longitude": 8
  },
  {
    "id": 215,
    "name": "Syria",
    "iso3": "SYR",
    "iso2": "SY",
    "phoneCode": "963",
    "currency": "SYP",
    "currencySymbol": "LS",
    "native": "سوريا",
    "region": "Asia",
    "latitude": 35,
    "longitude": 38
  },
  {
    "id": 216,
    "name": "Taiwan",
    "iso3": "TWN",
    "iso2": "TW",
    "phoneCode": "886",
    "currency": "TWD",
    "currencySymbol": "$",
    "native": "臺灣",
    "region": "Asia",
    "latitude": 23.5,
    "longitude": 121
  },
  {
    "id": 217,
    "name": "Tajikistan",
    "iso3": "TJK",
    "iso2": "TJ",
    "phoneCode": "992",
    "currency": "TJS",
    "currencySymbol": "SM",
    "native": "Тоҷикистон",
    "region": "Asia",
    "latitude": 39,
    "longitude": 71
  },
  {
    "id": 218,
    "name": "Tanzania",
    "iso3": "TZA",
    "iso2": "TZ",
    "phoneCode": "255",
    "currency": "TZS",
    "currencySymbol": "TSh",
    "native": "Tanzania",
    "region": "Africa",
    "latitude": -6,
    "longitude": 35
  },
  {
    "id": 219,
    "name": "Thailand",
    "iso3": "THA",
    "iso2": "TH",
    "phoneCode": "66",
    "currency": "THB",
    "currencySymbol": "฿",
    "native": "ประเทศไทย",
    "region": "Asia",
    "latitude": 15,
    "longitude": 100
  },
  {
    "id": 220,
    "name": "Togo",
    "iso3": "TGO",
    "iso2": "TG",
    "phoneCode": "228",
    "currency": "XOF",
    "currencySymbol": "CFA",
    "native": "Togo",
    "region": "Africa",
    "latitude": 8,
    "longitude": 1.16666666
  },
  {
    "id": 221,
    "name": "Tokelau",
    "iso3": "TKL",
    "iso2": "TK",
    "phoneCode": "690",
    "currency": "NZD",
    "currencySymbol": "$",
    "native": "Tokelau",
    "region": "Oceania",
    "latitude": -9,
    "longitude": -172
  },
  {
    "id": 222,
    "name": "Tonga",
    "iso3": "TON",
    "iso2": "TO",
    "phoneCode": "676",
    "currency": "TOP",
    "currencySymbol": "$",
    "native": "Tonga",
    "region": "Oceania",
    "latitude": -20,
    "longitude": -175
  },
  {
    "id": 223,
    "name": "Trinidad And Tobago",
    "iso3": "TTO",
    "iso2": "TT",
    "phoneCode": "+1-868",
    "currency": "TTD",
    "currencySymbol": "$",
    "native": "Trinidad and Tobago",
    "region": "Americas",
    "latitude": 11,
    "longitude": -61
  },
  {
    "id": 224,
    "name": "Tunisia",
    "iso3": "TUN",
    "iso2": "TN",
    "phoneCode": "216",
    "currency": "TND",
    "currencySymbol": "ت.د",
    "native": "تونس",
    "region": "Africa",
    "latitude": 34,
    "longitude": 9
  },
  {
    "id": 225,
    "name": "Turkey",
    "iso3": "TUR",
    "iso2": "TR",
    "phoneCode": "90",
    "currency": "TRY",
    "currencySymbol": "₺",
    "native": "Türkiye",
    "region": "Asia",
    "latitude": 39,
    "longitude": 35
  },
  {
    "id": 226,
    "name": "Turkmenistan",
    "iso3": "TKM",
    "iso2": "TM",
    "phoneCode": "993",
    "currency": "TMT",
    "currencySymbol": "T",
    "native": "Türkmenistan",
    "region": "Asia",
    "latitude": 40,
    "longitude": 60
  },
  {
    "id": 227,
    "name": "Turks And Caicos Islands",
    "iso3": "TCA",
    "iso2": "TC",
    "phoneCode": "+1-649",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "Turks and Caicos Islands",
    "region": "Americas",
    "latitude": 21.75,
    "longitude": -71.58333333
  },
  {
    "id": 228,
    "name": "Tuvalu",
    "iso3": "TUV",
    "iso2": "TV",
    "phoneCode": "688",
    "currency": "AUD",
    "currencySymbol": "$",
    "native": "Tuvalu",
    "region": "Oceania",
    "latitude": -8,
    "longitude": 178
  },
  {
    "id": 229,
    "name": "Uganda",
    "iso3": "UGA",
    "iso2": "UG",
    "phoneCode": "256",
    "currency": "UGX",
    "currencySymbol": "USh",
    "native": "Uganda",
    "region": "Africa",
    "latitude": 1,
    "longitude": 32
  },
  {
    "id": 230,
    "name": "Ukraine",
    "iso3": "UKR",
    "iso2": "UA",
    "phoneCode": "380",
    "currency": "UAH",
    "currencySymbol": "₴",
    "native": "Україна",
    "region": "Europe",
    "latitude": 49,
    "longitude": 32
  },
  {
    "id": 231,
    "name": "United Arab Emirates",
    "iso3": "ARE",
    "iso2": "AE",
    "phoneCode": "971",
    "currency": "AED",
    "currencySymbol": "إ.د",
    "native": "دولة الإمارات العربية المتحدة",
    "region": "Asia",
    "latitude": 24,
    "longitude": 54
  },
  {
    "id": 232,
    "name": "United Kingdom",
    "iso3": "GBR",
    "iso2": "GB",
    "phoneCode": "44",
    "currency": "GBP",
    "currencySymbol": "£",
    "native": "United Kingdom",
    "region": "Europe",
    "latitude": 54,
    "longitude": -2
  },
  {
    "id": 233,
    "name": "United States",
    "iso3": "USA",
    "iso2": "US",
    "phoneCode": "1",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "United States",
    "region": "Americas",
    "latitude": 38,
    "longitude": -97
  },
  {
    "id": 235,
    "name": "Uruguay",
    "iso3": "URY",
    "iso2": "UY",
    "phoneCode": "598",
    "currency": "UYU",
    "currencySymbol": "$",
    "native": "Uruguay",
    "region": "Americas",
    "latitude": -33,
    "longitude": -56
  },
  {
    "id": 236,
    "name": "Uzbekistan",
    "iso3": "UZB",
    "iso2": "UZ",
    "phoneCode": "998",
    "currency": "UZS",
    "currencySymbol": "лв",
    "native": "O‘zbekiston",
    "region": "Asia",
    "latitude": 41,
    "longitude": 64
  },
  {
    "id": 237,
    "name": "Vanuatu",
    "iso3": "VUT",
    "iso2": "VU",
    "phoneCode": "678",
    "currency": "VUV",
    "currencySymbol": "VT",
    "native": "Vanuatu",
    "region": "Oceania",
    "latitude": -16,
    "longitude": 167
  },
  {
    "id": 238,
    "name": "Vatican City State (Holy See)",
    "iso3": "VAT",
    "iso2": "VA",
    "phoneCode": "379",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Vaticano",
    "region": "Europe",
    "latitude": 41.9,
    "longitude": 12.45
  },
  {
    "id": 239,
    "name": "Venezuela",
    "iso3": "VEN",
    "iso2": "VE",
    "phoneCode": "58",
    "currency": "VEF",
    "currencySymbol": "Bs",
    "native": "Venezuela",
    "region": "Americas",
    "latitude": 8,
    "longitude": -66
  },
  {
    "id": 240,
    "name": "Vietnam",
    "iso3": "VNM",
    "iso2": "VN",
    "phoneCode": "84",
    "currency": "VND",
    "currencySymbol": "₫",
    "native": "Việt Nam",
    "region": "Asia",
    "latitude": 16.16666666,
    "longitude": 107.83333333
  },
  {
    "id": 241,
    "name": "Virgin Islands (British)",
    "iso3": "VGB",
    "iso2": "VG",
    "phoneCode": "+1-284",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "British Virgin Islands",
    "region": "Americas",
    "latitude": 18.431383,
    "longitude": -64.62305
  },
  {
    "id": 242,
    "name": "Virgin Islands (US)",
    "iso3": "VIR",
    "iso2": "VI",
    "phoneCode": "+1-340",
    "currency": "USD",
    "currencySymbol": "$",
    "native": "United States Virgin Islands",
    "region": "Americas",
    "latitude": 18.34,
    "longitude": -64.93
  },
  {
    "id": 243,
    "name": "Wallis And Futuna Islands",
    "iso3": "WLF",
    "iso2": "WF",
    "phoneCode": "681",
    "currency": "XPF",
    "currencySymbol": "₣",
    "native": "Wallis et Futuna",
    "region": "Oceania",
    "latitude": -13.3,
    "longitude": -176.2
  },
  {
    "id": 244,
    "name": "Western Sahara",
    "iso3": "ESH",
    "iso2": "EH",
    "phoneCode": "212",
    "currency": "MAD",
    "currencySymbol": "MAD",
    "native": "الصحراء الغربية",
    "region": "Africa",
    "latitude": 24.5,
    "longitude": -13
  },
  {
    "id": 245,
    "name": "Yemen",
    "iso3": "YEM",
    "iso2": "YE",
    "phoneCode": "967",
    "currency": "YER",
    "currencySymbol": "﷼",
    "native": "اليَمَن",
    "region": "Asia",
    "latitude": 15,
    "longitude": 48
  },
  {
    "id": 246,
    "name": "Zambia",
    "iso3": "ZMB",
    "iso2": "ZM",
    "phoneCode": "260",
    "currency": "ZMW",
    "currencySymbol": "ZK",
    "native": "Zambia",
    "region": "Africa",
    "latitude": -15,
    "longitude": 30
  },
  {
    "id": 247,
    "name": "Zimbabwe",
    "iso3": "ZWE",
    "iso2": "ZW",
    "phoneCode": "263",
    "currency": "ZWL",
    "currencySymbol": "$",
    "native": "Zimbabwe",
    "region": "Africa",
    "latitude": -20,
    "longitude": 30
  },
  {
    "id": 248,
    "name": "Kosovo",
    "iso3": "XKX",
    "iso2": "XK",
    "phoneCode": "383",
    "currency": "EUR",
    "currencySymbol": "€",
    "native": "Republika e Kosovës",
    "region": "Europe",
    "latitude": 42.5612909,
    "longitude": 20.3403035
  },
  {
    "id": 249,
    "name": "Curaçao",
    "iso3": "CUW",
    "iso2": "CW",
    "phoneCode": "599",
    "currency": "ANG",
    "currencySymbol": "ƒ",
    "native": "Curaçao",
    "region": "Americas",
    "latitude": 12.116667,
    "longitude": -68.933333
  },
  {
    "id": 250,
    "name": "Sint Maarten (Dutch part)",
    "iso3": "SXM",
    "iso2": "SX",
    "phoneCode": "1721",
    "currency": "ANG",
    "currencySymbol": "ƒ",
    "native": "Sint Maarten",
    "region": "Americas",
    "latitude": 18.033333,
    "longitude": -63.05
  }
] as any;
  }

  public async runAsync(): Promise<void> {
    await this.loadSeedEntityAsync();
    if (!this.shouldRun()) {
      return;
    }
    this.logger.info("Seeding " + this.name + "...");
    try {
      const data = await this.transformSeedDataAsync();
      if (data.length === 0) return;
      
      const chunkSize = 1000;
      let totalInserted = 0;
      for (let i = 0; i < data.length; i += chunkSize) {
        const chunk = data.slice(i, i + chunkSize);
        await this.repo.createQueryBuilder()
          .insert()
          .into(CountryEntity)
          .values(chunk)
          .orIgnore()
          .execute();
        totalInserted += chunk.length;
      }

      await this.updateSeedEntityAsync();
      this.logger.info("Seeding " + this.name + " finished. Total records: " + totalInserted);
      await this.postSeedAsync();
    } catch (ex) {
      this.logger.error(ex, "Seeding " + this.name + " failed");
      throw ex;
    }
  }

  constructor(
    dataSource: DataSource,
    @InjectRepository(CountryEntity) repo: Repository<CountryEntity>,
    @InjectPinoLogger(RefCountriesSeed.name) logger: PinoLogger,
  ) {
    super(dataSource, repo, logger);
  }

  protected equalityCheck(x: Partial<CountryEntity>, y: Partial<CountryEntity>): boolean {
    return (x as any).id ? x.id === y.id : (x as any).code === (y as any).code;
  }
  protected createFilter(): FindOptionsWhere<CountryEntity> { return {}; }
}
